[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["rm -rf node_modules/.cache && npm run build && npx drizzle-kit push --force"]

[start]
cmd = "npm run start"
