import type { Express } from "express";
import OpenAI from "openai";
import puppeteer from "puppeteer";
import { handleRevolutionaryAI, multiProviderAI } from "../ai-engine";
import {
  getUserAPIKeys,
  createAPIKey,
  updateAPIKey,
  deleteAPIKey,
  getAPIKeyUsage,
  getAPIBilling,
  getAPIDocumentation
} from "../api-management";
import { authenticateAPIKey, rateLimitAPIKey, logAPIUsage } from "../api-auth";
import { isAuthenticated } from "../auth";

const openai = process.env.OPENAI_API_KEY ? new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
  baseURL: 'https://api.deepseek.com',
}) : null;

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

async function generateAIPDF(req: any, res: any) {
  try {
    const { prompt, title = "AI Generated Document", format = "report" } = req.body;
    
    if (!prompt) {
      return res.status(400).json({
        success: false,
        error: "Prompt is required"
      });
    }

    console.log("🧠 AI PDF Generation: Starting content generation with OpenAI...");
    
    let generatedContent;
    if (openai) {
      const completion = await openai.chat.completions.create({
        model: "deepseek-chat",
        messages: [
          {
            role: "system",
            content: `You are a professional document writer. Generate high-quality, well-structured content based on the user's prompt. Format the content with proper headings, paragraphs, and structure suitable for a professional ${format}.`
          },
          {
            role: "user",
            content: prompt
          }
        ],
        max_tokens: 2000,
        temperature: 0.7
      });
      generatedContent = completion.choices[0].message.content;
    } else {
      const { quantumOpenAIEngine } = await import('../quantum-openai-engine');
      const quantumResponse = await quantumOpenAIEngine.generateQuantumResponse({
        model: "gpt-4o",
        messages: [
          {
            role: "system",
            content: `You are a professional document writer. Generate high-quality, well-structured content based on the user's prompt. Format the content with proper headings, paragraphs, and structure suitable for a professional ${format}.`
          },
          {
            role: "user",
            content: prompt
          }
        ],
        max_tokens: 2000,
        temperature: 0.7
      });
      generatedContent = quantumResponse.choices[0].message.content;
    }

    console.log("✅ AI Content Generated Successfully");

    const safeTitle = escapeHtml(title);
    const safeContent = escapeHtml(generatedContent).replace(/\n/g, '<br>');

    const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${safeTitle}</title>
      <style>
        body {
          font-family: 'Arial', sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px;
        }
        h1 {
          color: #2c3e50;
          border-bottom: 3px solid #3498db;
          padding-bottom: 10px;
          margin-bottom: 30px;
        }
        h2 {
          color: #2c3e50;
          margin-top: 30px;
          margin-bottom: 15px;
        }
        p {
          margin-bottom: 15px;
          text-align: justify;
        }
        .header {
          text-align: center;
          margin-bottom: 40px;
        }
        .footer {
          text-align: center;
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #ddd;
          color: #666;
          font-size: 12px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${safeTitle}</h1>
        <p>Generated by Simpleton™ AI</p>
      </div>
      
      <div class="content">
        ${safeContent}
      </div>
      
      <div class="footer">
        <p>Generated on ${new Date().toLocaleDateString()}</p>
        <p>Powered by Simpleton™ AI Intelligence Platform</p>
      </div>
    </body>
    </html>
    `;

    console.log("📄 Converting HTML to PDF using Puppeteer...");

    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    
    const page = await browser.newPage();
    await page.setContent(htmlContent);
    
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20px',
        right: '20px',
        bottom: '20px',
        left: '20px'
      }
    });
    
    await browser.close();
    
    console.log("✅ PDF Generated Successfully");

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf"`);
    res.send(pdfBuffer);

  } catch (error: any) {
    console.error("❌ AI PDF Generation Error:", error);
    res.status(500).json({
      success: false,
      error: "Failed to generate AI PDF",
      details: error.message
    });
  }
}

export function registerAIServiceRoutes(app: Express) {
  console.log('🔌 API Routes: Registering OpenAI-compatible routes for client applications');
  app.post('/api/openai/chat/completions', authenticateAPIKey, rateLimitAPIKey, logAPIUsage, (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));
  app.post('/api/openai/vision/analyze', authenticateAPIKey, rateLimitAPIKey, logAPIUsage, (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));
  app.get('/api/openai/models', authenticateAPIKey, rateLimitAPIKey, logAPIUsage, (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));

  app.post('/api/quantum/chat', (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));
  app.post('/api/quantum/vision', (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));
  app.get('/api/quantum/models', (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));

  app.post("/api/ai/generate-pdf", authenticateAPIKey, rateLimitAPIKey, generateAIPDF);

  app.get("/api/docs", getAPIDocumentation);

  app.get("/api/ai/all-models", (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));
  app.get("/api/ai/models/:provider", (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));
  app.get("/api/ai/capability/:capability", (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));
  app.get("/api/ai/top-models", (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));
  app.post("/api/ai/consensus", (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));

  app.get("/api/quantum-ticker-2056", (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));
  app.get("/api/quantum-ticker-2057", (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));
  app.get("/api/quantum-ticker-2057/companies", (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));
  app.get("/api/quantum-ticker-2057/models", (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));

  app.get("/api/ai/bulletproof/status", (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));
  app.get("/api/ai/providers", (req, res) => {
    const providers = multiProviderAI.getProviderStatus();
    const active = providers.filter(p => p.active);
    res.json({
      success: true,
      totalProviders: providers.length,
      activeProviders: active.length,
      providers: providers.map(p => ({
        name: p.name,
        active: p.active,
        models: p.models,
        type: p.type,
      })),
    });
  });
  app.get("/api/ai/stats", (req, res) => res.status(410).json({ error: "This endpoint has been retired" }));

  app.post("/api/ai/revolutionary", handleRevolutionaryAI);

  app.post("/api/customer/generate-key", async (req, res) => {
    try {
      const { customerName, customerEmail, tier = "free", endpoints = ["pricing", "ai"] } = req.body;
      
      if (!customerName || !customerEmail) {
        return res.status(400).json({ 
          error: "Customer name and email are required" 
        });
      }

      console.log('🔑 CUSTOMER KEY GENERATION: Creating key for', customerEmail);
      
      const apiKey = await createAPIKey(customerName, endpoints);
      
      res.json({
        success: true,
        message: "API key generated successfully! Start using our quantum data platform immediately.",
        apiKey: {
          keyId: apiKey.key,
          name: apiKey.name,
          tier: tier,
          endpoints: endpoints,
          rateLimit: tier === "free" ? "10/min, 1000/day" : "100/min, 10000/day",
          created: apiKey.created
        },
        gettingStarted: {
          documentation: "/api-docs",
          examples: {
            preciousMetals: "GET /api/pricing/latest",
            aiChat: "POST /api/quantum/chat",
            diamondPricing: "POST /api/diamond/pricing"
          },
          authentication: `Authorization: Bearer ${apiKey.key}`
        },
        revolutionaryAdvantage: "First quantum data platform with instant API access - no approval wait time!",
        timestamp: new Date().toISOString()
      });
    } catch (error: any) {
      console.error('❌ Customer key generation failed:', error);
      res.status(500).json({ 
        error: "Failed to generate API key",
        details: error.message 
      });
    }
  });

  app.get("/api/keys", isAuthenticated, (req, res) => getUserAPIKeys(req as any, res));
  app.post("/api/keys", isAuthenticated, (req, res) => createAPIKey(req as any, res));
  app.put("/api/keys/:id", isAuthenticated, (req, res) => updateAPIKey(req as any, res));
  app.delete("/api/keys/:id", isAuthenticated, (req, res) => deleteAPIKey(req as any, res));
  app.get("/api/keys/:id/usage", isAuthenticated, (req, res) => getAPIKeyUsage(req as any, res));

  app.get("/api/api-keys", async (req, res) => {
    try {
      const { getUserAPIKeys } = await import('../api-management');
      const keys = await getUserAPIKeys();
      res.json(keys);
    } catch (error: any) {
      res.status(500).json({ error: 'Failed to fetch API keys' });
    }
  });

  app.post("/api/api-keys", async (req, res) => {
    try {
      const { createAPIKey } = await import('../api-management');
      const { name, permissions } = req.body;
      if (!name) {
        return res.status(400).json({ error: 'Name is required' });
      }
      const key = await createAPIKey(name, permissions);
      res.status(201).json(key);
    } catch (error: any) {
      res.status(500).json({ error: 'Failed to create API key' });
    }
  });

  app.get("/api/usage/current", async (req, res) => {
    try {
      const { getAPIKeyUsage } = await import('../api-management');
      const usage = await getAPIKeyUsage();
      res.json(usage);
    } catch (error: any) {
      res.status(500).json({ error: 'Failed to fetch usage data' });
    }
  });

  app.get("/api/billing/current", async (req, res) => {
    try {
      const { getAPIBilling } = await import('../api-management');
      const billing = await getAPIBilling();
      res.json(billing);
    } catch (error: any) {
      res.status(500).json({ error: 'Failed to fetch billing data' });
    }
  });
}
