import { db } from "./db";
import { coins } from "@shared/schema";
import { sql } from "drizzle-orm";
import { pool } from "./db";

const newCoins = [
  {
    name: "Junk Silver - Washington Quarters ($1 Face Value)",
    type: "silver",
    yearStart: 1932,
    yearEnd: 1964,
    purity: "0.9000",
    weight: "0.7234",
    diameter: "24.30",
    thickness: "1.75",
    mintage: 500000000,
    description: "Pre-1965 Washington quarters containing 90% silver. Sold by face value as 'junk silver' for their silver content. $1 face value contains approximately 0.7234 troy oz of pure silver.",
    specifications: { composition: "90% silver, 10% copper", tradingUnit: "$1 face value", silverContentPerDollar: "0.7234 troy oz", designer: "John Flanagan" }
  },
  {
    name: "Junk Silver - Roosevelt Dimes ($1 Face Value)",
    type: "silver",
    yearStart: 1946,
    yearEnd: 1964,
    purity: "0.9000",
    weight: "0.7234",
    diameter: "17.91",
    thickness: "1.35",
    mintage: 800000000,
    description: "Pre-1965 Roosevelt dimes containing 90% silver. Traded in bulk by face value. $1 face value (10 dimes) contains approximately 0.7234 troy oz of pure silver.",
    specifications: { composition: "90% silver, 10% copper", tradingUnit: "$1 face value", silverContentPerDollar: "0.7234 troy oz", designer: "John R. Sinnock" }
  },
  {
    name: "Junk Silver - Walking Liberty Half Dollars ($1 Face Value)",
    type: "silver",
    yearStart: 1916,
    yearEnd: 1947,
    purity: "0.9000",
    weight: "0.7234",
    diameter: "30.60",
    thickness: "2.15",
    mintage: 400000000,
    description: "Pre-1965 Walking Liberty half dollars containing 90% silver. Among the most beautiful US coin designs. $1 face value (2 halves) contains approximately 0.7234 troy oz of pure silver.",
    specifications: { composition: "90% silver, 10% copper", tradingUnit: "$1 face value", silverContentPerDollar: "0.7234 troy oz", designer: "Adolph A. Weinman" }
  },
  {
    name: "Junk Silver - Franklin Half Dollars ($1 Face Value)",
    type: "silver",
    yearStart: 1948,
    yearEnd: 1963,
    purity: "0.9000",
    weight: "0.7234",
    diameter: "30.60",
    thickness: "2.15",
    mintage: 500000000,
    description: "Pre-1965 Franklin half dollars containing 90% silver. Features Benjamin Franklin on the obverse and the Liberty Bell on the reverse. $1 face value contains approximately 0.7234 troy oz of pure silver.",
    specifications: { composition: "90% silver, 10% copper", tradingUnit: "$1 face value", silverContentPerDollar: "0.7234 troy oz", designer: "John R. Sinnock" }
  },
  {
    name: "Junk Silver - Kennedy Half Dollars ($1 Face Value, 90%)",
    type: "silver",
    yearStart: 1964,
    yearEnd: 1964,
    purity: "0.9000",
    weight: "0.7234",
    diameter: "30.60",
    thickness: "2.15",
    mintage: 430000000,
    description: "1964 Kennedy half dollars containing 90% silver. The only year of 90% silver Kennedy halves before the composition was reduced in 1965. Extremely popular with collectors and investors.",
    specifications: { composition: "90% silver, 10% copper", tradingUnit: "$1 face value", silverContentPerDollar: "0.7234 troy oz", designer: "Gilroy Roberts / Frank Gasparro" }
  },
  {
    name: "Junk Silver - Mercury Dimes ($1 Face Value)",
    type: "silver",
    yearStart: 1916,
    yearEnd: 1945,
    purity: "0.9000",
    weight: "0.7234",
    diameter: "17.91",
    thickness: "1.35",
    mintage: 2000000000,
    description: "Pre-1965 Mercury dimes (officially Winged Liberty Head) containing 90% silver. One of the most iconic US coin designs. $1 face value contains approximately 0.7234 troy oz of pure silver.",
    specifications: { composition: "90% silver, 10% copper", tradingUnit: "$1 face value", silverContentPerDollar: "0.7234 troy oz", designer: "Adolph A. Weinman" }
  },
  {
    name: "War Nickel (Jefferson 35% Silver)",
    type: "silver",
    yearStart: 1942,
    yearEnd: 1945,
    purity: "0.3500",
    weight: "0.0563",
    diameter: "21.21",
    thickness: "1.95",
    mintage: 870000000,
    description: "Jefferson nickels minted 1942-1945 with 35% silver composition due to wartime nickel shortage. Identified by large mint mark (P, D, S) above Monticello on the reverse. The only US nickel with silver content.",
    specifications: { composition: "56% copper, 35% silver, 9% manganese", designer: "Felix Schlag", mintMarks: ["P", "D", "S"], silverContent: "0.05626 troy oz per coin", wartime: true }
  },
  {
    name: "Two Cent Piece",
    type: "copper",
    yearStart: 1864,
    yearEnd: 1873,
    purity: "0.9500",
    weight: "0.2139",
    diameter: "23.00",
    thickness: "1.80",
    mintage: 45600000,
    description: "First US coin to bear the motto 'In God We Trust'. Made of 95% copper (bronze). Discontinued due to lack of public demand. The 1864 Small Motto variety is the key date.",
    specifications: { composition: "95% copper, 5% tin and zinc", designer: "James B. Longacre", edge: "Plain", keyDates: ["1864 Small Motto", "1872", "1873 Closed 3"] }
  },
  {
    name: "Three Cent Silver (Trime)",
    type: "silver",
    yearStart: 1851,
    yearEnd: 1873,
    purity: "0.9000",
    weight: "0.0250",
    diameter: "14.00",
    thickness: "0.80",
    mintage: 42000000,
    description: "The smallest US silver coin ever produced. Created to facilitate purchase of 3-cent postage stamps. Three design types exist. Later dates are scarce as production shifted to the Three Cent Nickel.",
    specifications: { composition: "90% silver, 10% copper (Type 2-3); 75% silver (Type 1)", designer: "James B. Longacre", edge: "Plain", types: ["Type 1 (1851-1853)", "Type 2 (1854-1858)", "Type 3 (1859-1873)"] }
  },
  {
    name: "Three Cent Nickel",
    type: "copper",
    yearStart: 1865,
    yearEnd: 1889,
    purity: "0.7500",
    weight: "0.0694",
    diameter: "17.90",
    thickness: "1.20",
    mintage: 31000000,
    description: "Copper-nickel three cent piece introduced after the Civil War. Features Liberty head with coronet on obverse and Roman numeral III on reverse. Later dates (1880s) have very low mintages.",
    specifications: { composition: "75% copper, 25% nickel", designer: "James B. Longacre", edge: "Plain", keyDates: ["1877 Proof Only", "1878 Proof Only", "1883", "1884", "1885", "1886", "1887", "1888"] }
  },
  {
    name: "Twenty Cent Piece",
    type: "silver",
    yearStart: 1875,
    yearEnd: 1878,
    purity: "0.9000",
    weight: "0.1608",
    diameter: "22.00",
    thickness: "1.50",
    mintage: 1350000,
    description: "One of the shortest-lived US coin denominations. Easily confused with the quarter dollar, leading to its quick demise. Only business strikes in 1875-1876; 1877-1878 proof only.",
    specifications: { composition: "90% silver, 10% copper", designer: "William Barber", edge: "Plain", mintMarks: ["None", "CC", "S"], keyDates: ["1876-CC (only 10,000 minted)", "1877 Proof only", "1878 Proof only"] }
  },
  {
    name: "Seated Liberty Quarter — No Motto",
    type: "silver",
    yearStart: 1838,
    yearEnd: 1865,
    purity: "0.9000",
    weight: "0.2009",
    diameter: "24.30",
    thickness: "1.75",
    mintage: 50000000,
    description: "Features seated Liberty on the obverse without the motto 'In God We Trust'. Many Civil War era dates are scarce. Includes rare Carson City, New Orleans, and San Francisco mint issues.",
    specifications: { composition: "90% silver, 10% copper", designer: "Christian Gobrecht", edge: "Reeded", mintMarks: ["None", "O", "S"], varieties: ["No Drapery (1838-1840)", "With Drapery (1840-1865)", "Arrows and Rays (1853)", "Arrows (1854-1855)"] }
  },
  {
    name: "Seated Liberty Quarter — With Motto",
    type: "silver",
    yearStart: 1866,
    yearEnd: 1891,
    purity: "0.9000",
    weight: "0.2009",
    diameter: "24.30",
    thickness: "1.75",
    mintage: 60000000,
    description: "Seated Liberty quarter with 'In God We Trust' motto added to the reverse above the eagle. Includes rare Carson City (CC) dates from the Nevada mint.",
    specifications: { composition: "90% silver, 10% copper", designer: "Christian Gobrecht", edge: "Reeded", mintMarks: ["None", "CC", "S"], keyDates: ["1873-CC Arrows", "1878-CC", "1879-1890 (low mintage)"] }
  },
  {
    name: "Seated Liberty Half Dime",
    type: "silver",
    yearStart: 1837,
    yearEnd: 1873,
    purity: "0.9000",
    weight: "0.0402",
    diameter: "15.50",
    thickness: "1.00",
    mintage: 50000000,
    description: "Small silver coin predating the nickel five-cent piece. Features seated Liberty on the obverse. The last US silver coin smaller than a dime.",
    specifications: { composition: "90% silver, 10% copper", designer: "Christian Gobrecht", edge: "Reeded", mintMarks: ["None", "O", "S"], varieties: ["No Stars (1837-1838)", "With Stars (1838-1859)", "Legend (1860-1873)"] }
  },
  {
    name: "Seated Liberty Dime — Legend Obverse",
    type: "silver",
    yearStart: 1860,
    yearEnd: 1891,
    purity: "0.9000",
    weight: "0.0804",
    diameter: "17.91",
    thickness: "1.35",
    mintage: 100000000,
    description: "Final subtype of the Seated Liberty dime with 'United States of America' moved to the obverse. Includes scarce Carson City and San Francisco issues from the 1870s.",
    specifications: { composition: "90% silver, 10% copper", designer: "Christian Gobrecht", edge: "Reeded", mintMarks: ["None", "CC", "S"], keyDates: ["1873-CC", "1874-CC"] }
  },
  {
    name: "US Mint Silver Proof Set",
    type: "silver",
    yearStart: 1992,
    yearEnd: null,
    purity: "0.9000",
    weight: "0.6250",
    diameter: "38.10",
    thickness: "2.40",
    mintage: 500000,
    description: "Annual proof set from the US Mint containing silver versions of circulating denominations. Dimes, quarters, and half dollars struck in 90% silver with mirror-like proof finish.",
    specifications: { composition: "90% silver proof coins", mintMark: "S (San Francisco)", contents: ["Silver Dime", "Silver Quarter(s)", "Silver Half Dollar", "Dollar", "Cent", "Nickel"], packaging: "Government-issued lens case" }
  },
  {
    name: "US Mint Uncirculated Coin Set",
    type: "copper",
    yearStart: 1947,
    yearEnd: null,
    purity: "0.0000",
    weight: "0.5000",
    diameter: "30.00",
    thickness: "2.00",
    mintage: 1000000,
    description: "Annual uncirculated mint set containing one example of each circulating denomination from Philadelphia and Denver. Pre-1965 sets contain 90% silver coins and carry significant premiums.",
    specifications: { composition: "Various (depends on year)", mints: ["P", "D"], contents: "One of each denomination from each mint", packaging: "Government-issued cardboard holders" }
  },
  {
    name: "US Commemorative Silver Dollar - Various",
    type: "silver",
    yearStart: 1983,
    yearEnd: null,
    purity: "0.9000",
    weight: "0.8594",
    diameter: "38.10",
    thickness: "2.98",
    mintage: 500000,
    description: "Modern US commemorative silver dollars issued to honor significant people, places, and events. Each year features different designs. Legal tender with $1 face value.",
    specifications: { composition: "90% silver, 10% copper", weight: "26.73 grams", designer: "Various", mintMarks: ["P", "D", "S", "W"], notable: ["1986 Statue of Liberty", "1991 Mount Rushmore", "2014 Baseball Hall of Fame"] }
  },
  {
    name: "US Commemorative $5 Gold - Various",
    type: "gold",
    yearStart: 1986,
    yearEnd: null,
    purity: "0.9000",
    weight: "0.2709",
    diameter: "21.59",
    thickness: "1.50",
    mintage: 100000,
    description: "Modern US commemorative gold $5 coins honoring significant people, events, and institutions. Limited mintages make many issues scarce. Contains approximately 0.2418 troy oz of pure gold.",
    specifications: { composition: "90% gold, 10% copper", designer: "Various", mintMark: "W (West Point)", notable: ["1986 Statue of Liberty", "1992 Olympics", "2014 Baseball Hall of Fame"] }
  },
  {
    name: "Isle of Man Cat Crown (Silver)",
    type: "silver",
    yearStart: 1988,
    yearEnd: null,
    purity: "0.9990",
    weight: "1.0000",
    diameter: "38.61",
    thickness: "3.00",
    mintage: 30000,
    description: "Beloved collector series featuring a different cat breed each year. Struck in .999 fine silver with exquisite detail. Extremely popular with both coin collectors and cat enthusiasts worldwide.",
    specifications: { composition: "99.9% silver", mint: "Pobjoy Mint", denomination: "1 Crown", breeds: ["Manx", "Persian", "Siamese", "Maine Coon", "Norwegian Forest Cat", "Bengal"] }
  },
  {
    name: "Isle of Man Cat Crown (Gold)",
    type: "gold",
    yearStart: 1988,
    yearEnd: null,
    purity: "0.9999",
    weight: "0.1000",
    diameter: "17.95",
    thickness: "1.20",
    mintage: 5000,
    description: "Gold version of the popular Cat Crown series featuring a different cat breed each year. Struck in .9999 fine gold with limited mintages. Highly sought after by collectors.",
    specifications: { composition: "99.99% gold", mint: "Pobjoy Mint", denomination: "1/10 Crown", sizes: ["1/25 oz", "1/10 oz", "1/5 oz", "1/2 oz", "1 oz"] }
  },
  {
    name: "Austrian 1 Ducat Gold (Original Strike)",
    type: "gold",
    yearStart: 1612,
    yearEnd: 1915,
    purity: "0.9860",
    weight: "0.1107",
    diameter: "19.75",
    thickness: "0.70",
    mintage: 5000000,
    description: "Original strike Austrian gold ducats, not restrikes. Features Emperor Franz Joseph I (later dates) or earlier Habsburg rulers. Thin, high-purity gold coins with centuries of trading history.",
    specifications: { composition: "98.6% gold", weight: "3.4909 grams", mint: "Vienna Mint", fineGoldContent: "0.1107 troy oz", note: "Original strikes, not 1915 restrike" }
  },
  {
    name: "Swiss Vreneli 20 Franc Gold",
    type: "gold",
    yearStart: 1897,
    yearEnd: 1949,
    purity: "0.9000",
    weight: "0.1867",
    diameter: "21.00",
    thickness: "1.25",
    mintage: 60000000,
    description: "Iconic Swiss gold coin featuring 'Vreneli' (a young Swiss maiden with Alpine background) on the obverse. One of the most popular European gold coins for investment. Contains 0.1867 troy oz of pure gold.",
    specifications: { composition: "90% gold, 10% copper", weight: "6.4516 grams", mint: "Swiss Federal Mint (Bern)", fineGoldContent: "0.1867 troy oz", designer: "Fritz Ulysse Landry" }
  },
  {
    name: "German 20 Mark Gold (Unified Empire)",
    type: "gold",
    yearStart: 1871,
    yearEnd: 1915,
    purity: "0.9000",
    weight: "0.2304",
    diameter: "22.50",
    thickness: "1.30",
    mintage: 100000000,
    description: "Gold 20 Mark coins from the unified German Empire featuring various German state rulers including Prussia, Bavaria, Saxony, and others. Popular with European gold investors.",
    specifications: { composition: "90% gold, 10% copper", weight: "7.965 grams", fineGoldContent: "0.2304 troy oz", states: ["Prussia", "Bavaria", "Saxony", "Baden", "Hamburg", "Württemberg"], mints: ["A (Berlin)", "D (Munich)", "E (Muldenhütten)", "F (Stuttgart)", "G (Karlsruhe)", "J (Hamburg)"] }
  },
  {
    name: "Russian Gold Chervonets (10 Roubles)",
    type: "gold",
    yearStart: 1923,
    yearEnd: 1982,
    purity: "0.9000",
    weight: "0.2489",
    diameter: "22.60",
    thickness: "1.70",
    mintage: 7000000,
    description: "Soviet gold coin modeled on the Tsarist 10 ruble gold piece. Features a peasant sowing grain. Primarily struck 1975-1982 as gold bullion for international trade. Contains 0.2489 troy oz of pure gold.",
    specifications: { composition: "90% gold, 10% copper", weight: "8.6026 grams", fineGoldContent: "0.2489 troy oz", mint: "Leningrad Mint", designer: "A.F. Vasyutinsky" }
  },
  {
    name: "Indian Gold Guinea (British India)",
    type: "gold",
    yearStart: 1862,
    yearEnd: 1918,
    purity: "0.9170",
    weight: "0.2354",
    diameter: "22.00",
    thickness: "1.40",
    mintage: 50000000,
    description: "Gold sovereign equivalent minted for use in British India. Features Queen Victoria, King Edward VII, or King George V. Known as the 'Mohur' or Indian gold piece. Highly collectible.",
    specifications: { composition: "91.7% gold, 8.3% copper", weight: "7.988 grams", fineGoldContent: "0.2354 troy oz", mints: ["Bombay", "Calcutta"], rulers: ["Victoria", "Edward VII", "George V"] }
  },
  {
    name: "New Zealand Gold Kiwi (1 oz)",
    type: "gold",
    yearStart: 2009,
    yearEnd: null,
    purity: "0.9999",
    weight: "1.0000",
    diameter: "38.74",
    thickness: "2.80",
    mintage: 5000,
    description: "Legal tender gold bullion coin from New Zealand featuring the iconic kiwi bird. Struck in .9999 fine gold with very limited annual mintages. Highly sought by collectors for its unique design.",
    specifications: { composition: "99.99% gold", mint: "New Zealand Mint", denomination: "$200 NZD", designer: "Ian Rank-Broadley (obverse)" }
  },
  {
    name: "Somalian Silver Elephant (1 oz)",
    type: "silver",
    yearStart: 2004,
    yearEnd: null,
    purity: "0.9999",
    weight: "1.0000",
    diameter: "39.00",
    thickness: "2.90",
    mintage: 500000,
    description: "Annual bullion series featuring a different African elephant design each year. Struck in .9999 fine silver by the Bavarian State Mint. Yearly design changes make older dates increasingly valuable.",
    specifications: { composition: "99.99% silver", mint: "Bavarian State Mint (Germany)", denomination: "100 Shillings", annualDesignChange: true, securityFeatures: ["Micro-engraving", "Light-diffraction"] }
  },
  {
    name: "Armenian Noah's Ark Silver (1 oz)",
    type: "silver",
    yearStart: 2011,
    yearEnd: null,
    purity: "0.9990",
    weight: "1.0000",
    diameter: "38.61",
    thickness: "3.00",
    mintage: 200000,
    description: "Legal tender silver bullion coin from Armenia featuring Noah's Ark with Mount Ararat in the background. Produced by the Geiger Edelmetalle mint. Low premiums make it popular with silver stackers.",
    specifications: { composition: "99.9% silver", mint: "Geiger Edelmetalle (Germany)", denomination: "500 Dram", designer: "Eduard Kurghinyan", sizes: ["1/4 oz", "1/2 oz", "1 oz", "5 oz", "10 oz", "1 kg"] }
  },
  {
    name: "Tuvalu Dragon Silver (1 oz)",
    type: "silver",
    yearStart: 2017,
    yearEnd: null,
    purity: "0.9999",
    weight: "1.0000",
    diameter: "40.60",
    thickness: "3.20",
    mintage: 250000,
    description: "Perth Mint struck silver bullion coin for the island nation of Tuvalu featuring a powerful Chinese dragon design. Very popular in Asian markets. Limited annual mintages add collector appeal.",
    specifications: { composition: "99.99% silver", mint: "Perth Mint (Australia)", denomination: "$1 TVD", designer: "Perth Mint design team" }
  },
  {
    name: "Perth Mint Swan Silver (1 oz)",
    type: "silver",
    yearStart: 2017,
    yearEnd: null,
    purity: "0.9999",
    weight: "1.0000",
    diameter: "40.60",
    thickness: "3.20",
    mintage: 25000,
    description: "Ultra-limited silver bullion coin featuring the iconic Australian black swan. New design each year with very low mintages of only 25,000 per year. Among the most collectible modern silver coins.",
    specifications: { composition: "99.99% silver", mint: "Perth Mint (Australia)", denomination: "$1 AUD", annualDesignChange: true, limitedMintage: true }
  },
  {
    name: "Queen's Beasts - Lion of England (2 oz Silver)",
    type: "silver",
    yearStart: 2016,
    yearEnd: 2021,
    purity: "0.9999",
    weight: "2.0000",
    diameter: "38.61",
    thickness: "6.00",
    mintage: 200000,
    description: "First coin in the Royal Mint's Queen's Beasts series featuring the Lion of England. Ten heraldic beasts that stood guard at Queen Elizabeth II's coronation in 1953. Struck in 2 troy oz of .9999 silver.",
    specifications: { composition: "99.99% silver", mint: "Royal Mint (UK)", denomination: "£5 GBP", designer: "Jody Clark", series: "Queen's Beasts (1 of 10)" }
  },
  {
    name: "Queen's Beasts - Red Dragon of Wales (2 oz Silver)",
    type: "silver",
    yearStart: 2017,
    yearEnd: 2021,
    purity: "0.9999",
    weight: "2.0000",
    diameter: "38.61",
    thickness: "6.00",
    mintage: 200000,
    description: "The Red Dragon of Wales from the Queen's Beasts series. Features the fierce Welsh dragon, a symbol used since King Henry VII. Struck in 2 troy oz of .9999 fine silver.",
    specifications: { composition: "99.99% silver", mint: "Royal Mint (UK)", denomination: "£5 GBP", designer: "Jody Clark", series: "Queen's Beasts (2 of 10)" }
  },
  {
    name: "Queen's Beasts - Unicorn of Scotland (2 oz Silver)",
    type: "silver",
    yearStart: 2017,
    yearEnd: 2021,
    purity: "0.9999",
    weight: "2.0000",
    diameter: "38.61",
    thickness: "6.00",
    mintage: 200000,
    description: "The Unicorn of Scotland from the Queen's Beasts series. The unicorn has been a symbol of Scotland for centuries. Struck in 2 troy oz of .9999 fine silver by the Royal Mint.",
    specifications: { composition: "99.99% silver", mint: "Royal Mint (UK)", denomination: "£5 GBP", designer: "Jody Clark", series: "Queen's Beasts (3 of 10)" }
  },
  {
    name: "Queen's Beasts - Black Bull of Clarence (2 oz Silver)",
    type: "silver",
    yearStart: 2018,
    yearEnd: 2021,
    purity: "0.9999",
    weight: "2.0000",
    diameter: "38.61",
    thickness: "6.00",
    mintage: 200000,
    description: "The Black Bull of Clarence from the Queen's Beasts series. Symbolizes the House of York, introduced by King Edward IV. Struck in 2 troy oz of .9999 fine silver.",
    specifications: { composition: "99.99% silver", mint: "Royal Mint (UK)", denomination: "£5 GBP", designer: "Jody Clark", series: "Queen's Beasts (4 of 10)" }
  },
  {
    name: "Queen's Beasts - Falcon of the Plantagenets (2 oz Silver)",
    type: "silver",
    yearStart: 2019,
    yearEnd: 2021,
    purity: "0.9999",
    weight: "2.0000",
    diameter: "38.61",
    thickness: "6.00",
    mintage: 200000,
    description: "The Falcon of the Plantagenets from the Queen's Beasts series. Badge of King Edward III representing power and ambition. Struck in 2 troy oz of .9999 fine silver.",
    specifications: { composition: "99.99% silver", mint: "Royal Mint (UK)", denomination: "£5 GBP", designer: "Jody Clark", series: "Queen's Beasts (5 of 10)" }
  },
  {
    name: "Queen's Beasts - Completer Coin (2 oz Silver)",
    type: "silver",
    yearStart: 2021,
    yearEnd: 2021,
    purity: "0.9999",
    weight: "2.0000",
    diameter: "38.61",
    thickness: "6.00",
    mintage: 200000,
    description: "The final coin in the Queen's Beasts series featuring all ten beasts together around the Royal Arms. The ultimate collector piece to complete the series.",
    specifications: { composition: "99.99% silver", mint: "Royal Mint (UK)", denomination: "£5 GBP", designer: "Jody Clark", series: "Queen's Beasts (Completer)" }
  },
  {
    name: "American Innovation Dollar - Delaware",
    type: "copper",
    yearStart: 2019,
    yearEnd: 2019,
    purity: "0.0000",
    weight: "0.2893",
    diameter: "26.50",
    thickness: "2.00",
    mintage: 250000000,
    description: "First coin in the American Innovation $1 Coin Program honoring innovation from each state. Delaware features Annie Jump Cannon's star classification system.",
    specifications: { composition: "Manganese brass clad", designer: "Various", mintMarks: ["P", "D"], series: "American Innovation $1 Coin Program" }
  },
  {
    name: "American Innovation Dollar Series (2019-2033)",
    type: "copper",
    yearStart: 2019,
    yearEnd: 2033,
    purity: "0.0000",
    weight: "0.2893",
    diameter: "26.50",
    thickness: "2.00",
    mintage: 250000000,
    description: "14-year program issuing $1 coins honoring innovation and innovators from each US state, DC, and territories. Four designs released per year.",
    specifications: { composition: "Manganese brass clad", designer: "Various", mintMarks: ["P", "D"], totalCoins: "57 designs over 14 years", obverse: "Statue of Liberty" }
  },
  {
    name: "Native American (Sacagawea) Dollar Series",
    type: "copper",
    yearStart: 2009,
    yearEnd: null,
    purity: "0.0000",
    weight: "0.2893",
    diameter: "26.50",
    thickness: "2.00",
    mintage: 5000000,
    description: "Annual dollar coin series honoring Native American contributions. Features Sacagawea on the obverse with annually changing reverse designs celebrating Native American achievements.",
    specifications: { composition: "Manganese brass clad", designer: "Glenna Goodacre (obverse)", mintMarks: ["P", "D"], edgeLettering: true, themes: ["Agriculture", "Trade Routes", "Hospitality", "Space Program", "Code Talkers"] }
  },
  {
    name: "American Gold Eagle with W Mint Mark Privy (1 oz)",
    type: "gold",
    yearStart: 2021,
    yearEnd: null,
    purity: "0.9167",
    weight: "1.0909",
    diameter: "32.70",
    thickness: "2.87",
    mintage: 500000,
    description: "Type 2 American Gold Eagle with redesigned reverse featuring an eagle portrait by Jennie Norris. The 2021 transition year with both Type 1 and Type 2 is especially collectible.",
    specifications: { composition: "91.67% gold, 3% silver, 5.33% copper", designer: "Augustus Saint-Gaudens / Jennie Norris", mintMarks: ["W"], type: "Type 2 (2021-present)" }
  },
  {
    name: "Canadian Maple Leaf Silver with Privy Mark",
    type: "silver",
    yearStart: 2014,
    yearEnd: null,
    purity: "0.9999",
    weight: "1.0000",
    diameter: "38.00",
    thickness: "3.29",
    mintage: 50000,
    description: "Limited edition Canadian Silver Maple Leaf with special privy marks. Various privy marks include Horse, Sheep, Monkey, Rooster, Dog, Pig, and others from the Chinese Zodiac series.",
    specifications: { composition: "99.99% silver", mint: "Royal Canadian Mint", denomination: "$5 CAD", privyMarks: ["Horse", "Sheep", "Monkey", "Rooster", "Dog", "Pig", "Rat", "Ox", "Tiger"] }
  },
  {
    name: "Canadian Maple Leaf Gold with Privy Mark",
    type: "gold",
    yearStart: 2014,
    yearEnd: null,
    purity: "0.9999",
    weight: "1.0000",
    diameter: "30.00",
    thickness: "2.80",
    mintage: 5000,
    description: "Limited edition Canadian Gold Maple Leaf with special privy marks. Features Chinese Zodiac animal privy marks with very limited mintages. Highly collectible.",
    specifications: { composition: "99.99% gold", mint: "Royal Canadian Mint", denomination: "$200 CAD", privyMarks: ["Horse", "Sheep", "Monkey", "Rooster", "Dog", "Pig"] }
  },
  {
    name: "Australian Kookaburra Silver with Privy Mark (1 oz)",
    type: "silver",
    yearStart: 2010,
    yearEnd: null,
    purity: "0.9999",
    weight: "1.0000",
    diameter: "40.60",
    thickness: "3.20",
    mintage: 50000,
    description: "Limited edition Perth Mint Silver Kookaburra with special privy marks. Features various privy marks including country flags, events, and symbols. New kookaburra design each year.",
    specifications: { composition: "99.99% silver", mint: "Perth Mint (Australia)", denomination: "$1 AUD", annualDesignChange: true, privyMarkTypes: ["Country flags", "Anniversary marks", "Event marks"] }
  },
  {
    name: "American Silver Eagle Type 2 with S Mint Mark",
    type: "silver",
    yearStart: 2021,
    yearEnd: null,
    purity: "0.9990",
    weight: "1.0000",
    diameter: "40.60",
    thickness: "2.98",
    mintage: 200000,
    description: "Type 2 American Silver Eagle struck at San Francisco with S mint mark. Features redesigned eagle reverse by Emily Damstra. San Francisco strikes are limited and collectible.",
    specifications: { composition: "99.9% silver", designer: "Adolph A. Weinman / Emily Damstra", mintMark: "S (San Francisco)", type: "Type 2 (2021-present)" }
  },
  {
    name: "Barber Half Dollar",
    type: "silver",
    yearStart: 1892,
    yearEnd: 1915,
    purity: "0.9000",
    weight: "0.3618",
    diameter: "30.60",
    thickness: "2.15",
    mintage: 140000000,
    description: "Features the Liberty Head (Barber) design used across dimes, quarters, and half dollars. The 1892-O and 1893-S are key dates. Many were melted, making higher-grade survivors scarce.",
    specifications: { composition: "90% silver, 10% copper", designer: "Charles E. Barber", edge: "Reeded", mintMarks: ["None", "D", "O", "S"], keyDates: ["1892-O", "1893-S", "1904-S", "1913-S", "1914-S", "1915-S"] }
  },
  {
    name: "Standing Liberty Quarter",
    type: "silver",
    yearStart: 1916,
    yearEnd: 1930,
    purity: "0.9000",
    weight: "0.2009",
    diameter: "24.30",
    thickness: "1.75",
    mintage: 230000000,
    description: "One of the most artistically beautiful US coins. Features a full-length figure of Liberty with shield and olive branch. The 1916 is extremely rare with only 52,000 struck.",
    specifications: { composition: "90% silver, 10% copper", designer: "Hermon A. MacNeil", edge: "Reeded", types: ["Type 1 (1916-1917)", "Type 2 (1917-1930)"], keyDates: ["1916", "1918/7-S", "1919-D", "1921", "1923-S"] }
  },
  {
    name: "Trade Dollar",
    type: "silver",
    yearStart: 1873,
    yearEnd: 1885,
    purity: "0.9000",
    weight: "0.8750",
    diameter: "38.10",
    thickness: "2.40",
    mintage: 36000000,
    description: "Minted specifically for trade with China and other Asian nations. Slightly heavier than the standard silver dollar. Business strikes 1873-1878; proof only 1879-1885.",
    specifications: { composition: "90% silver, 10% copper", designer: "William Barber", edge: "Reeded", mintMarks: ["None", "CC", "S"], keyDates: ["1878-CC", "1884 Proof", "1885 Proof"] }
  },
  {
    name: "Eisenhower Dollar (Silver Clad)",
    type: "silver",
    yearStart: 1971,
    yearEnd: 1976,
    purity: "0.4000",
    weight: "0.3161",
    diameter: "38.10",
    thickness: "2.58",
    mintage: 50000000,
    description: "Silver-clad version of the Eisenhower dollar with 40% silver content. Produced only at San Francisco in proof and uncirculated finishes. Includes the 1976 Bicentennial reverse.",
    specifications: { composition: "40% silver, 60% copper (outer: 80% silver, 20% copper; core: 20.9% silver)", designer: "Frank Gasparro", mintMark: "S (San Francisco)", bicentennial: "1976 reverse by Dennis R. Williams" }
  },
  {
    name: "Kennedy Half Dollar (40% Silver)",
    type: "silver",
    yearStart: 1965,
    yearEnd: 1970,
    purity: "0.4000",
    weight: "0.1479",
    diameter: "30.60",
    thickness: "2.15",
    mintage: 500000000,
    description: "Reduced silver Kennedy half dollars with 40% silver content. Produced 1965-1970 as transition from 90% silver. The 1970-D is a key date with only proof production at Denver.",
    specifications: { composition: "40% silver, 60% copper", designer: "Gilroy Roberts / Frank Gasparro", mintMarks: ["None (1965-1967)", "D", "S"], silverContent: "0.1479 troy oz per coin" }
  },
  {
    name: "Palladium American Eagle (1 oz)",
    type: "palladium",
    yearStart: 2017,
    yearEnd: null,
    purity: "0.9995",
    weight: "1.0000",
    diameter: "34.00",
    thickness: "2.50",
    mintage: 15000,
    description: "The first US palladium bullion coin. Features Adolph A. Weinman's Winged Liberty (Mercury dime) obverse and his 1907 ANA medal reverse. $25 face value. Very limited mintages.",
    specifications: { composition: "99.95% palladium", designer: "Adolph A. Weinman", mintMark: "W (West Point)", denomination: "$25", faceValue: "$25 USD" }
  },
  {
    name: "American Platinum Eagle (1 oz)",
    type: "platinum",
    yearStart: 1997,
    yearEnd: null,
    purity: "0.9995",
    weight: "1.0000",
    diameter: "32.70",
    thickness: "2.39",
    mintage: 100000,
    description: "The highest face value US coin at $100. Bullion version features Statue of Liberty obverse and soaring eagle reverse. Proof versions have annually changing reverse designs.",
    specifications: { composition: "99.95% platinum", designer: "John Mercanti (obverse)", mintMarks: ["W (proof)", "None (bullion)"], denomination: "$100", sizes: ["1/10 oz", "1/4 oz", "1/2 oz", "1 oz"] }
  },
  {
    name: "British Britannia Gold (1 oz)",
    type: "gold",
    yearStart: 1987,
    yearEnd: null,
    purity: "0.9999",
    weight: "1.0000",
    diameter: "32.69",
    thickness: "2.84",
    mintage: 100000,
    description: "Flagship gold bullion coin of the Royal Mint. Features Britannia, the female personification of Britain. Upgraded to .9999 fine gold in 2013. UK legal tender with £100 face value (tax advantages).",
    specifications: { composition: "99.99% gold (2013-present); 91.67% gold (1987-2012)", mint: "Royal Mint (UK)", denomination: "£100 GBP", designer: "Philip Nathan (original)", securityFeatures: ["Animation effect", "Surface micro-text", "Tincture lines", "Latent image"] }
  },
  {
    name: "British Britannia Silver (1 oz)",
    type: "silver",
    yearStart: 1997,
    yearEnd: null,
    purity: "0.9990",
    weight: "1.0000",
    diameter: "38.61",
    thickness: "2.70",
    mintage: 2000000,
    description: "Silver version of the Royal Mint's Britannia bullion coin. Features iconic Britannia design with trident and shield. UK legal tender at £2 face value. Popular worldwide investment coin.",
    specifications: { composition: "99.9% silver", mint: "Royal Mint (UK)", denomination: "£2 GBP", designer: "Philip Nathan", securityFeatures: ["Animation effect", "Surface micro-text", "Tincture lines", "Latent image"] }
  },
  {
    name: "South African Krugerrand Gold (1 oz)",
    type: "gold",
    yearStart: 1967,
    yearEnd: null,
    purity: "0.9167",
    weight: "1.0909",
    diameter: "32.77",
    thickness: "2.84",
    mintage: 60000000,
    description: "The world's first modern gold bullion coin and still the most widely held. Features Paul Kruger and a springbok antelope. Contains exactly 1 troy oz of pure gold in a durable 22kt alloy.",
    specifications: { composition: "91.67% gold, 8.33% copper", mint: "South African Mint (Pretoria)", designer: "Coert Steynberg", fineGoldContent: "1.0000 troy oz", noFaceValue: true }
  },
  {
    name: "Mexican Gold Libertad (1 oz)",
    type: "gold",
    yearStart: 1981,
    yearEnd: null,
    purity: "0.9990",
    weight: "1.0000",
    diameter: "34.50",
    thickness: "2.69",
    mintage: 10000,
    description: "Mexico's premier gold bullion coin featuring the Winged Victory (Angel of Independence) statue and the Mexican coat of arms. Extremely low mintages make it one of the most scarce sovereign gold bullion coins.",
    specifications: { composition: "99.9% gold", mint: "Casa de Moneda de México", designer: "Various", noFaceValue: true, sizes: ["1/20 oz", "1/10 oz", "1/4 oz", "1/2 oz", "1 oz"] }
  },
  {
    name: "Mexican Silver Libertad (1 oz)",
    type: "silver",
    yearStart: 1982,
    yearEnd: null,
    purity: "0.9990",
    weight: "1.0000",
    diameter: "40.00",
    thickness: "3.00",
    mintage: 1000000,
    description: "Mexico's flagship silver bullion coin featuring the Winged Victory statue. Lower mintages than most sovereign silver bullion coins create higher premiums. No face value denomination.",
    specifications: { composition: "99.9% silver", mint: "Casa de Moneda de México", noFaceValue: true, sizes: ["1/20 oz", "1/10 oz", "1/4 oz", "1/2 oz", "1 oz", "2 oz", "5 oz", "1 kg"] }
  },
  {
    name: "Chinese Silver Panda (30g)",
    type: "silver",
    yearStart: 1983,
    yearEnd: null,
    purity: "0.9990",
    weight: "0.9646",
    diameter: "40.00",
    thickness: "2.98",
    mintage: 8000000,
    description: "China's iconic silver bullion coin featuring a new panda design each year. Changed from 1 oz to 30 grams in 2016. Annual design changes make older dates highly collectible.",
    specifications: { composition: "99.9% silver", mint: "Various Chinese Mints", denomination: "10 Yuan", weight: "30 grams (2016-present); 1 troy oz (1983-2015)", annualDesignChange: true }
  },
  {
    name: "Chinese Gold Panda (30g)",
    type: "gold",
    yearStart: 1982,
    yearEnd: null,
    purity: "0.9990",
    weight: "0.9646",
    diameter: "32.00",
    thickness: "2.50",
    mintage: 500000,
    description: "China's flagship gold bullion coin with annually changing panda designs. Changed from 1 oz to 30 grams in 2016. Each year's unique design makes them highly collectible.",
    specifications: { composition: "99.9% gold", mint: "Various Chinese Mints", denomination: "500 Yuan", weight: "30 grams (2016-present); 1 troy oz (1982-2015)", annualDesignChange: true }
  },
  {
    name: "Austrian Philharmonic Gold (1 oz)",
    type: "gold",
    yearStart: 1989,
    yearEnd: null,
    purity: "0.9999",
    weight: "1.0000",
    diameter: "37.00",
    thickness: "2.00",
    mintage: 5000000,
    description: "Europe's most popular gold bullion coin. Features the Great Organ of the Vienna Musikverein concert hall and orchestral instruments. Denominated in euros (€100).",
    specifications: { composition: "99.99% gold", mint: "Austrian Mint (Münze Österreich)", denomination: "€100 EUR", designer: "Thomas Pesendorfer" }
  },
  {
    name: "Austrian Philharmonic Silver (1 oz)",
    type: "silver",
    yearStart: 2008,
    yearEnd: null,
    purity: "0.9990",
    weight: "1.0000",
    diameter: "37.00",
    thickness: "3.20",
    mintage: 20000000,
    description: "Silver version of Europe's most popular bullion coin series. Features the Vienna Philharmonic orchestra instruments. One of the world's best-selling silver bullion coins.",
    specifications: { composition: "99.9% silver", mint: "Austrian Mint (Münze Österreich)", denomination: "€1.50 EUR", designer: "Thomas Pesendorfer" }
  },
];

async function seedNewCoins() {
  console.log(`🪙 Preparing to insert ${newCoins.length} new coins...`);

  try {
    await pool.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS coins_name_unique ON coins (name);
    `);
    console.log("✅ Unique index on coins.name ensured");

    const result = await db.insert(coins).values(newCoins).onConflictDoNothing({ target: coins.name }).returning({ id: coins.id });

    console.log(`✅ Successfully inserted ${result.length} new coins (${newCoins.length - result.length} already existed)`);
  } catch (error) {
    console.error("❌ Error seeding coins:", error);
  } finally {
    await pool.end();
    process.exit(0);
  }
}

seedNewCoins();
