import { pool } from "./db";

async function seedNewRolexModels() {
  console.log("🕰️ Seeding new Rolex models...");

  const models = [
    // DATEJUST
    {
      reference_number: '126200',
      name: 'Datejust 36',
      collection: 'Datejust',
      category: 'Classic/Dress',
      sub_category: 'Date',
      production_start_year: 2019,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 36.0,
      case_material: 'Oystersteel',
      case_thickness: 11.8,
      lug_width: 20.0,
      dial_colors: ['Silver', 'Blue', 'Black', 'Green', 'Mint Green'],
      dial_type: 'Sunburst',
      index_markers: 'Stick',
      bezel_type: 'Smooth',
      bezel_material: 'Oystersteel',
      bezel_colors: ['Steel'],
      movement_caliber: '3235',
      power_reserve: 70,
      bracelet_types: ['Oyster', 'Jubilee'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 7150,
      current_market_value: 7500,
      currency: 'USD',
      rarity_score: 3,
      collectibility_notes: 'Entry-level Datejust, very popular daily wear',
      notable_features: ['Calibre 3235', 'Chromalight display', '70-hour power reserve'],
      description: 'The Datejust 36 in Oystersteel with calibre 3235 movement offers enhanced precision and power reserve.',
    },
    {
      reference_number: '126233',
      name: 'Datejust 36 Two-Tone',
      collection: 'Datejust',
      category: 'Classic/Dress',
      sub_category: 'Date',
      production_start_year: 2019,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 36.0,
      case_material: 'Oystersteel and Yellow Gold',
      case_thickness: 11.8,
      lug_width: 20.0,
      dial_colors: ['Champagne', 'Black', 'Silver', 'Palm motif'],
      dial_type: 'Sunburst',
      index_markers: 'Stick',
      bezel_type: 'Fluted',
      bezel_material: '18ct Yellow Gold',
      bezel_colors: ['Yellow Gold'],
      movement_caliber: '3235',
      power_reserve: 70,
      bracelet_types: ['Jubilee', 'Oyster'],
      bracelet_material: 'Oystersteel and Yellow Gold',
      clasp_type: 'Oysterclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 12300,
      current_market_value: 11500,
      currency: 'USD',
      rarity_score: 3,
      collectibility_notes: 'Classic two-tone Datejust combination',
      notable_features: ['Rolesor combination', 'Fluted bezel', 'Jubilee bracelet'],
      description: 'The Datejust 36 in Oystersteel and yellow gold Rolesor with fluted bezel.',
    },
    {
      reference_number: '126331',
      name: 'Datejust 41 Everose Rolesor',
      collection: 'Datejust',
      category: 'Classic/Dress',
      sub_category: 'Date',
      production_start_year: 2017,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 41.0,
      case_material: 'Oystersteel and Everose Gold',
      case_thickness: 11.9,
      lug_width: 21.0,
      dial_colors: ['Sundust', 'Chocolate', 'Slate', 'Black'],
      dial_type: 'Sunburst',
      index_markers: 'Stick',
      bezel_type: 'Fluted',
      bezel_material: '18ct Everose Gold',
      bezel_colors: ['Everose Gold'],
      movement_caliber: '3235',
      power_reserve: 70,
      bracelet_types: ['Jubilee', 'Oyster'],
      bracelet_material: 'Oystersteel and Everose Gold',
      clasp_type: 'Oysterclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 14050,
      current_market_value: 13000,
      currency: 'USD',
      rarity_score: 4,
      collectibility_notes: 'Elegant Everose gold combination, warm tone',
      notable_features: ['Everose Rolesor', 'Fluted bezel', 'Sundust dial option'],
      description: 'The Datejust 41 in Oystersteel and Everose gold with distinctive warm tones.',
    },
    {
      reference_number: '116233',
      name: 'Datejust 36 Two-Tone (Vintage)',
      collection: 'Datejust',
      category: 'Classic/Dress',
      sub_category: 'Date',
      production_start_year: 2004,
      production_end_year: 2016,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 36.0,
      case_material: 'Oystersteel and Yellow Gold',
      case_thickness: 12.0,
      lug_width: 20.0,
      dial_colors: ['Champagne', 'Black', 'Silver', 'White'],
      dial_type: 'Sunburst',
      index_markers: 'Stick',
      bezel_type: 'Fluted',
      bezel_material: '18ct Yellow Gold',
      bezel_colors: ['Yellow Gold'],
      movement_caliber: '3135',
      power_reserve: 48,
      bracelet_types: ['Jubilee', 'Oyster'],
      bracelet_material: 'Oystersteel and Yellow Gold',
      clasp_type: 'Oysterclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 9550,
      current_market_value: 8500,
      currency: 'USD',
      rarity_score: 4,
      collectibility_notes: 'Previous-generation two-tone with cal. 3135',
      notable_features: ['Calibre 3135', 'Classic Rolesor', 'Superlative Chronometer'],
      description: 'The previous-generation Datejust 36 two-tone with the proven calibre 3135 movement.',
    },
    {
      reference_number: '126284RBR',
      name: 'Datejust 36 Diamond Bezel',
      collection: 'Datejust',
      category: 'Luxury/Dress',
      sub_category: 'Date',
      production_start_year: 2019,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 36.0,
      case_material: 'Oystersteel and White Gold',
      case_thickness: 11.8,
      lug_width: 20.0,
      dial_colors: ['Silver', 'Aubergine', 'Olive Green', 'Palm motif'],
      dial_type: 'Sunburst',
      index_markers: 'Diamond',
      bezel_type: 'Diamond-set',
      bezel_material: '18ct White Gold',
      bezel_colors: ['White Gold', 'Diamonds'],
      movement_caliber: '3235',
      power_reserve: 70,
      bracelet_types: ['Jubilee', 'Oyster'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 13550,
      current_market_value: 14000,
      currency: 'USD',
      rarity_score: 5,
      collectibility_notes: 'Diamond-set bezel adds luxury touch to steel Datejust',
      notable_features: ['Diamond-set bezel', 'White gold bezel', 'Diamond hour markers'],
      description: 'The Datejust 36 with a diamond-set bezel in 18ct white gold on an Oystersteel case.',
    },
    {
      reference_number: '278274',
      name: 'Lady-Datejust 31',
      collection: 'Lady-Datejust',
      category: 'Classic/Dress',
      sub_category: 'Date',
      production_start_year: 2019,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 31.0,
      case_material: 'Oystersteel and White Gold',
      case_thickness: 10.9,
      lug_width: 17.0,
      dial_colors: ['Silver', 'Blue', 'Mint Green', 'Aubergine'],
      dial_type: 'Sunburst',
      index_markers: 'Roman',
      bezel_type: 'Fluted',
      bezel_material: '18ct White Gold',
      bezel_colors: ['White Gold'],
      movement_caliber: '2236',
      power_reserve: 55,
      bracelet_types: ['Jubilee', 'Oyster'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 9800,
      current_market_value: 9500,
      currency: 'USD',
      rarity_score: 3,
      collectibility_notes: 'Mid-size ladies Datejust with Syloxi hairspring',
      notable_features: ['Calibre 2236', 'Syloxi hairspring', 'Fluted bezel'],
      description: 'The Lady-Datejust 31 in Oystersteel with white gold fluted bezel, featuring the calibre 2236.',
    },
    {
      reference_number: '279171',
      name: 'Lady-Datejust 28 Everose',
      collection: 'Lady-Datejust',
      category: 'Luxury/Dress',
      sub_category: 'Date',
      production_start_year: 2015,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 28.0,
      case_material: 'Oystersteel and Everose Gold',
      case_thickness: 10.3,
      lug_width: 15.0,
      dial_colors: ['Sundust', 'Chocolate', 'Silver', 'White'],
      dial_type: 'Sunburst',
      index_markers: 'Roman',
      bezel_type: 'Fluted',
      bezel_material: '18ct Everose Gold',
      bezel_colors: ['Everose Gold'],
      movement_caliber: '2236',
      power_reserve: 55,
      bracelet_types: ['Jubilee'],
      bracelet_material: 'Oystersteel and Everose Gold',
      clasp_type: 'Crownclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 12150,
      current_market_value: 11000,
      currency: 'USD',
      rarity_score: 4,
      collectibility_notes: 'Compact ladies Datejust with Everose gold accents',
      notable_features: ['Everose Rolesor', 'Calibre 2236', 'Compact 28mm size'],
      description: 'The Lady-Datejust 28 in Oystersteel and Everose gold with Jubilee bracelet.',
    },

    // DAY-DATE
    {
      reference_number: '228235',
      name: 'Day-Date 40 Everose Gold',
      collection: 'Day-Date',
      category: 'Luxury/Dress',
      sub_category: 'Day-Date',
      production_start_year: 2015,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: '18ct Everose Gold',
      case_thickness: 12.4,
      lug_width: 21.0,
      dial_colors: ['Sundust', 'Chocolate', 'Olive Green', 'Eisenkiesel'],
      dial_type: 'Sunburst',
      index_markers: 'Roman',
      bezel_type: 'Fluted',
      bezel_material: '18ct Everose Gold',
      bezel_colors: ['Everose Gold'],
      movement_caliber: '3255',
      power_reserve: 70,
      bracelet_types: ['President'],
      bracelet_material: '18ct Everose Gold',
      clasp_type: 'Crownclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Day', 'Date', 'Cyclops lens'],
      original_retail_price: 38550,
      current_market_value: 42000,
      currency: 'USD',
      rarity_score: 6,
      collectibility_notes: 'Flagship Day-Date in warm Everose gold',
      notable_features: ['President bracelet', 'Day display in full', 'Calibre 3255'],
      description: 'The Day-Date 40 in 18ct Everose gold with fluted bezel and President bracelet.',
    },
    {
      reference_number: '118238',
      name: 'Day-Date 36 Yellow Gold (Vintage)',
      collection: 'Day-Date',
      category: 'Luxury/Dress',
      sub_category: 'Day-Date',
      production_start_year: 2000,
      production_end_year: 2015,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 36.0,
      case_material: '18ct Yellow Gold',
      case_thickness: 13.0,
      lug_width: 20.0,
      dial_colors: ['Champagne', 'White', 'Black', 'Silver'],
      dial_type: 'Sunburst',
      index_markers: 'Stick',
      bezel_type: 'Fluted',
      bezel_material: '18ct Yellow Gold',
      bezel_colors: ['Yellow Gold'],
      movement_caliber: '3155',
      power_reserve: 48,
      bracelet_types: ['President'],
      bracelet_material: '18ct Yellow Gold',
      clasp_type: 'Crownclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Day', 'Date', 'Cyclops lens'],
      original_retail_price: 30000,
      current_market_value: 28000,
      currency: 'USD',
      rarity_score: 5,
      collectibility_notes: 'Classic 36mm Day-Date with proven 3155 movement',
      notable_features: ['Calibre 3155', 'Classic 36mm size', 'Full gold President bracelet'],
      description: 'The classic Day-Date 36 in 18ct yellow gold, the quintessential "President" watch.',
    },
    {
      reference_number: '228349RBR',
      name: 'Day-Date 40 White Gold Diamond Bezel',
      collection: 'Day-Date',
      category: 'Luxury/Dress',
      sub_category: 'Day-Date',
      production_start_year: 2015,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: '18ct White Gold',
      case_thickness: 12.4,
      lug_width: 21.0,
      dial_colors: ['Silver', 'Meteorite', 'Mother of Pearl'],
      dial_type: 'Sunburst',
      index_markers: 'Diamond',
      bezel_type: 'Diamond-set',
      bezel_material: '18ct White Gold',
      bezel_colors: ['White Gold', 'Diamonds'],
      movement_caliber: '3255',
      power_reserve: 70,
      bracelet_types: ['President'],
      bracelet_material: '18ct White Gold',
      clasp_type: 'Crownclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Day', 'Date', 'Cyclops lens'],
      original_retail_price: 58500,
      current_market_value: 55000,
      currency: 'USD',
      rarity_score: 7,
      collectibility_notes: 'Top-tier Day-Date with diamond bezel and dial',
      notable_features: ['Diamond-set bezel', 'Baguette diamond hour markers', 'White gold President bracelet'],
      description: 'The Day-Date 40 in 18ct white gold with diamond-set bezel, the ultimate luxury timepiece.',
    },

    // SUBMARINER
    {
      reference_number: '114060',
      name: 'Submariner No-Date',
      collection: 'Submariner',
      category: 'Sport/Dive',
      sub_category: 'No-Date',
      production_start_year: 2012,
      production_end_year: 2020,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: 'Oystersteel',
      case_thickness: 12.5,
      lug_width: 20.0,
      dial_colors: ['Black'],
      dial_type: 'Matte',
      index_markers: 'Luminous',
      bezel_type: 'Unidirectional rotating',
      bezel_material: 'Cerachrom',
      bezel_colors: ['Black'],
      movement_caliber: '3130',
      power_reserve: 48,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterlock with Glidelock',
      water_resistance: 300,
      functions: ['Hours', 'Minutes', 'Seconds'],
      original_retail_price: 7500,
      current_market_value: 11000,
      currency: 'USD',
      rarity_score: 6,
      collectibility_notes: 'Last 40mm no-date Sub, highly sought after since discontinuation',
      notable_features: ['No-date purist design', 'Cerachrom bezel insert', 'Maxi dial'],
      description: 'The last 40mm Submariner without date, discontinued in 2020 and commanding strong premiums.',
    },
    {
      reference_number: '16610',
      name: 'Submariner Date (5-digit)',
      collection: 'Submariner',
      category: 'Sport/Dive',
      sub_category: 'Date',
      production_start_year: 1989,
      production_end_year: 2010,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: 'Stainless Steel',
      case_thickness: 12.5,
      lug_width: 20.0,
      dial_colors: ['Black'],
      dial_type: 'Matte',
      index_markers: 'Luminous',
      bezel_type: 'Unidirectional rotating',
      bezel_material: 'Aluminum',
      bezel_colors: ['Black'],
      movement_caliber: '3135',
      power_reserve: 48,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Stainless Steel',
      clasp_type: 'Oysterlock',
      water_resistance: 300,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 5000,
      current_market_value: 10500,
      currency: 'USD',
      rarity_score: 6,
      collectibility_notes: 'The legendary 5-digit Submariner, a cornerstone reference',
      notable_features: ['Aluminum bezel insert', 'Drilled lug holes', 'SEL bracelet (later versions)'],
      description: 'The iconic 5-digit Submariner Date, produced for over 20 years and beloved by collectors.',
    },
    {
      reference_number: '5513',
      name: 'Submariner No-Date (Vintage)',
      collection: 'Submariner',
      category: 'Vintage',
      sub_category: 'No-Date',
      production_start_year: 1962,
      production_end_year: 1989,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: 'Stainless Steel',
      case_thickness: 12.5,
      lug_width: 20.0,
      dial_colors: ['Black'],
      dial_type: 'Matte',
      index_markers: 'Luminous',
      bezel_type: 'Unidirectional rotating',
      bezel_material: 'Aluminum',
      bezel_colors: ['Black'],
      movement_caliber: '1520/1530',
      power_reserve: 48,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Stainless Steel',
      clasp_type: 'Fliplock',
      water_resistance: 200,
      functions: ['Hours', 'Minutes', 'Seconds'],
      original_retail_price: 300,
      current_market_value: 15000,
      currency: 'USD',
      rarity_score: 7,
      collectibility_notes: 'Longest-produced Submariner reference, many dial variations prized by collectors',
      notable_features: ['Meters first dial', 'Gilt dials (early)', 'Tritium lume', 'Multiple dial variants'],
      description: 'The Submariner 5513, produced for 27 years with numerous sought-after dial variations.',
    },
    {
      reference_number: '1680',
      name: 'Submariner Date "Red Sub"',
      collection: 'Submariner',
      category: 'Vintage',
      sub_category: 'Date',
      production_start_year: 1967,
      production_end_year: 1979,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: 'Stainless Steel',
      case_thickness: 12.5,
      lug_width: 20.0,
      dial_colors: ['Black'],
      dial_type: 'Matte',
      index_markers: 'Luminous',
      bezel_type: 'Unidirectional rotating',
      bezel_material: 'Aluminum',
      bezel_colors: ['Black'],
      movement_caliber: '1575',
      power_reserve: 48,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Stainless Steel',
      clasp_type: 'Fliplock',
      water_resistance: 200,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 350,
      current_market_value: 25000,
      currency: 'USD',
      rarity_score: 8,
      collectibility_notes: 'First Submariner with date. "Red" text versions (Mark I-VI) are highly collectible',
      notable_features: ['Red "SUBMARINER" text', 'First Sub with date', 'Multiple Mark variants', 'Tritium lume'],
      description: 'The first Submariner with a date function. Early "Red Sub" dials with red text are extremely collectible.',
    },

    // GMT-MASTER
    {
      reference_number: '16710',
      name: 'GMT-Master II (Vintage)',
      collection: 'GMT-Master II',
      category: 'Sport/Travel',
      sub_category: 'GMT',
      production_start_year: 1989,
      production_end_year: 2007,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: 'Stainless Steel',
      case_thickness: 12.0,
      lug_width: 20.0,
      dial_colors: ['Black'],
      dial_type: 'Matte',
      index_markers: 'Luminous',
      bezel_type: 'Bidirectional rotating',
      bezel_material: 'Aluminum',
      bezel_colors: ['Black', 'Red/Blue (Pepsi)', 'Red/Black (Coke)'],
      movement_caliber: '3185/3186',
      power_reserve: 48,
      bracelet_types: ['Oyster', 'Jubilee'],
      bracelet_material: 'Stainless Steel',
      clasp_type: 'Oysterlock',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'GMT', 'Cyclops lens'],
      original_retail_price: 4500,
      current_market_value: 14000,
      currency: 'USD',
      rarity_score: 7,
      collectibility_notes: 'Last aluminum bezel GMT-Master II, available in multiple bezel colors',
      notable_features: ['Aluminum bezel insert', 'Independent hour hand', 'Drilled lug holes'],
      description: 'The 5-digit GMT-Master II with aluminum bezel in Pepsi, Coke, or all-black configurations.',
    },
    {
      reference_number: '1675',
      name: 'GMT-Master "Pepsi" (Vintage)',
      collection: 'GMT-Master',
      category: 'Vintage',
      sub_category: 'GMT',
      production_start_year: 1959,
      production_end_year: 1980,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: 'Stainless Steel',
      case_thickness: 12.0,
      lug_width: 20.0,
      dial_colors: ['Black'],
      dial_type: 'Gilt/Matte',
      index_markers: 'Luminous',
      bezel_type: 'Bidirectional rotating',
      bezel_material: 'Aluminum',
      bezel_colors: ['Red/Blue (Pepsi)'],
      movement_caliber: '1575',
      power_reserve: 48,
      bracelet_types: ['Oyster', 'Jubilee'],
      bracelet_material: 'Stainless Steel',
      clasp_type: 'Fliplock',
      water_resistance: 50,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'GMT', 'Cyclops lens'],
      original_retail_price: 250,
      current_market_value: 30000,
      currency: 'USD',
      rarity_score: 9,
      collectibility_notes: 'One of the most iconic vintage Rolex references. Gilt dials command huge premiums',
      notable_features: ['Pointed crown guard', 'Gilt dial (early)', 'Pepsi bezel', 'Hack feature added later'],
      description: 'The legendary vintage GMT-Master 1675 with Pepsi bezel, worn by pilots and travelers worldwide.',
    },
    {
      reference_number: '126720VTNR',
      name: 'GMT-Master II "Sprite" Left-Handed',
      collection: 'GMT-Master II',
      category: 'Sport/Travel',
      sub_category: 'GMT',
      production_start_year: 2022,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: 'Oystersteel',
      case_thickness: 13.0,
      lug_width: 20.0,
      dial_colors: ['Black'],
      dial_type: 'Lacquer',
      index_markers: 'Luminous',
      bezel_type: 'Bidirectional rotating',
      bezel_material: 'Cerachrom',
      bezel_colors: ['Green/Black'],
      movement_caliber: '3285',
      power_reserve: 70,
      bracelet_types: ['Jubilee', 'Oyster'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterclasp with Easylink',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'GMT', 'Cyclops lens'],
      original_retail_price: 10750,
      current_market_value: 18000,
      currency: 'USD',
      rarity_score: 7,
      collectibility_notes: 'First left-handed Rolex with crown on left side, nicknamed "Sprite" or "Destro"',
      notable_features: ['Left-handed crown at 9 o\'clock', 'Green/black Cerachrom bezel', 'Jubilee bracelet'],
      description: 'The first left-handed Rolex GMT-Master II with crown on the left side and green/black "Sprite" bezel.',
    },
    {
      reference_number: '126718GRNR',
      name: 'GMT-Master II Yellow Gold Green/Black',
      collection: 'GMT-Master II',
      category: 'Luxury/Sport',
      sub_category: 'GMT',
      production_start_year: 2023,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: '18ct Yellow Gold',
      case_thickness: 13.0,
      lug_width: 20.0,
      dial_colors: ['Black'],
      dial_type: 'Lacquer',
      index_markers: 'Luminous',
      bezel_type: 'Bidirectional rotating',
      bezel_material: 'Cerachrom',
      bezel_colors: ['Green/Black'],
      movement_caliber: '3285',
      power_reserve: 70,
      bracelet_types: ['Jubilee'],
      bracelet_material: '18ct Yellow Gold',
      clasp_type: 'Oysterclasp with Easylink',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'GMT', 'Cyclops lens'],
      original_retail_price: 42050,
      current_market_value: 46000,
      currency: 'USD',
      rarity_score: 7,
      collectibility_notes: 'Full gold GMT with green/black Sprite bezel, highly desirable',
      notable_features: ['Full yellow gold', 'Green/black Cerachrom bezel', 'Jubilee bracelet'],
      description: 'The GMT-Master II in 18ct yellow gold with green and black Cerachrom bezel.',
    },

    // DAYTONA
    {
      reference_number: '116515LN',
      name: 'Cosmograph Daytona Everose Oysterflex',
      collection: 'Cosmograph Daytona',
      category: 'Sport/Racing',
      sub_category: 'Chronograph',
      production_start_year: 2015,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: '18ct Everose Gold',
      case_thickness: 12.2,
      lug_width: 20.0,
      dial_colors: ['Chocolate', 'Sundust', 'Black', 'Meteorite'],
      dial_type: 'Sunburst',
      index_markers: 'Applied',
      bezel_type: 'Tachymeter',
      bezel_material: 'Cerachrom',
      bezel_colors: ['Black'],
      movement_caliber: '4130',
      power_reserve: 72,
      bracelet_types: ['Oysterflex'],
      bracelet_material: 'Elastomer with metal blade',
      clasp_type: 'Oysterlock',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Chronograph', 'Tachymeter'],
      original_retail_price: 29550,
      current_market_value: 35000,
      currency: 'USD',
      rarity_score: 7,
      collectibility_notes: 'First Daytona on rubber strap, sporty luxury combination',
      notable_features: ['Oysterflex bracelet', 'Cerachrom bezel', 'Everose gold case'],
      description: 'The Cosmograph Daytona in 18ct Everose gold on the innovative Oysterflex bracelet.',
    },
    {
      reference_number: '116518LN',
      name: 'Cosmograph Daytona Yellow Gold Oysterflex',
      collection: 'Cosmograph Daytona',
      category: 'Sport/Racing',
      sub_category: 'Chronograph',
      production_start_year: 2017,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: '18ct Yellow Gold',
      case_thickness: 12.2,
      lug_width: 20.0,
      dial_colors: ['Champagne', 'Black', 'White Mother of Pearl'],
      dial_type: 'Sunburst',
      index_markers: 'Applied',
      bezel_type: 'Tachymeter',
      bezel_material: 'Cerachrom',
      bezel_colors: ['Black'],
      movement_caliber: '4130',
      power_reserve: 72,
      bracelet_types: ['Oysterflex'],
      bracelet_material: 'Elastomer with metal blade',
      clasp_type: 'Oysterlock',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Chronograph', 'Tachymeter'],
      original_retail_price: 28800,
      current_market_value: 32000,
      currency: 'USD',
      rarity_score: 6,
      collectibility_notes: 'Yellow gold Daytona on Oysterflex, modern sporty look',
      notable_features: ['Oysterflex bracelet', 'Cerachrom tachymeter bezel', 'Yellow gold case'],
      description: 'The Cosmograph Daytona in 18ct yellow gold with Oysterflex bracelet and Cerachrom bezel.',
    },
    {
      reference_number: '116503',
      name: 'Cosmograph Daytona Two-Tone',
      collection: 'Cosmograph Daytona',
      category: 'Sport/Racing',
      sub_category: 'Chronograph',
      production_start_year: 2016,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: 'Oystersteel and Yellow Gold',
      case_thickness: 12.2,
      lug_width: 20.0,
      dial_colors: ['Champagne', 'White', 'Black', 'White Mother of Pearl'],
      dial_type: 'Sunburst',
      index_markers: 'Applied',
      bezel_type: 'Tachymeter',
      bezel_material: '18ct Yellow Gold',
      bezel_colors: ['Yellow Gold'],
      movement_caliber: '4130',
      power_reserve: 72,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Oystersteel and Yellow Gold',
      clasp_type: 'Oysterlock with Easylink',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Chronograph', 'Tachymeter'],
      original_retail_price: 19550,
      current_market_value: 22000,
      currency: 'USD',
      rarity_score: 5,
      collectibility_notes: 'Two-tone Daytona offers Rolesor value proposition',
      notable_features: ['Rolesor combination', 'Metal tachymeter bezel', 'Column wheel chronograph'],
      description: 'The Cosmograph Daytona in Oystersteel and yellow gold Rolesor on Oyster bracelet.',
    },
    {
      reference_number: '6239',
      name: 'Cosmograph Daytona "Paul Newman"',
      collection: 'Cosmograph Daytona',
      category: 'Vintage',
      sub_category: 'Chronograph',
      production_start_year: 1963,
      production_end_year: 1969,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 37.0,
      case_material: 'Stainless Steel',
      case_thickness: 14.0,
      lug_width: 19.0,
      dial_colors: ['White', 'Black'],
      dial_type: 'Exotic',
      index_markers: 'Printed',
      bezel_type: 'Tachymeter',
      bezel_material: 'Stainless Steel',
      bezel_colors: ['Steel'],
      movement_caliber: '722-1 (Valjoux 72)',
      power_reserve: 48,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Stainless Steel',
      clasp_type: 'Fliplock',
      water_resistance: 30,
      functions: ['Hours', 'Minutes', 'Seconds', 'Chronograph', 'Tachymeter'],
      original_retail_price: 210,
      current_market_value: 300000,
      currency: 'USD',
      rarity_score: 10,
      collectibility_notes: 'The original "Paul Newman" Daytona. Exotic dials fetch millions at auction',
      notable_features: ['Pump pushers', 'Exotic "Paul Newman" dial', 'Valjoux 72 movement', 'Acrylic crystal'],
      description: 'The legendary ref. 6239 Cosmograph Daytona, the original "Paul Newman" reference.',
    },
    {
      reference_number: '6263',
      name: 'Cosmograph Daytona Pump Pushers',
      collection: 'Cosmograph Daytona',
      category: 'Vintage',
      sub_category: 'Chronograph',
      production_start_year: 1970,
      production_end_year: 1987,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 37.0,
      case_material: 'Stainless Steel',
      case_thickness: 14.0,
      lug_width: 19.0,
      dial_colors: ['Black', 'White', 'Silver'],
      dial_type: 'Sigma/Exotic',
      index_markers: 'Printed',
      bezel_type: 'Tachymeter',
      bezel_material: 'Acrylic/Stainless Steel',
      bezel_colors: ['Black'],
      movement_caliber: '727 (Valjoux 727)',
      power_reserve: 48,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Stainless Steel',
      clasp_type: 'Fliplock',
      water_resistance: 30,
      functions: ['Hours', 'Minutes', 'Seconds', 'Chronograph', 'Tachymeter'],
      original_retail_price: 450,
      current_market_value: 200000,
      currency: 'USD',
      rarity_score: 9,
      collectibility_notes: 'Last manually wound Daytona with pump pushers. "Big Red" Daytona text is iconic',
      notable_features: ['Pump pushers', 'Acrylic black bezel', 'Valjoux 727 movement', '"Big Red" Daytona text'],
      description: 'The ref. 6263 Daytona with pump pushers and acrylic bezel, the last hand-wound Daytona.',
    },

    // EXPLORER
    {
      reference_number: '214270',
      name: 'Explorer 39mm (Discontinued)',
      collection: 'Explorer',
      category: 'Sport/Adventure',
      sub_category: 'Time Only',
      production_start_year: 2010,
      production_end_year: 2021,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 39.0,
      case_material: 'Oystersteel',
      case_thickness: 11.5,
      lug_width: 20.0,
      dial_colors: ['Black'],
      dial_type: 'Lacquer',
      index_markers: 'Chromalight 3/6/9',
      bezel_type: 'Smooth',
      bezel_material: 'Oystersteel',
      bezel_colors: ['Steel'],
      movement_caliber: '3132',
      power_reserve: 48,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterlock with Easylink',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds'],
      original_retail_price: 6550,
      current_market_value: 9000,
      currency: 'USD',
      rarity_score: 6,
      collectibility_notes: 'Discontinued 39mm size beloved by enthusiasts, replaced by 36mm 124270',
      notable_features: ['39mm case size', 'Chromalight lume', '3/6/9 Explorer dial'],
      description: 'The discontinued 39mm Explorer, preferred by many collectors over the current 36mm version.',
    },
    {
      reference_number: '216570',
      name: 'Explorer II 42mm (Previous Gen)',
      collection: 'Explorer II',
      category: 'Sport/Adventure',
      sub_category: 'GMT',
      production_start_year: 2011,
      production_end_year: 2021,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 42.0,
      case_material: 'Oystersteel',
      case_thickness: 12.5,
      lug_width: 21.0,
      dial_colors: ['Black', 'White (Polar)'],
      dial_type: 'Lacquer',
      index_markers: 'Luminous',
      bezel_type: 'Fixed 24-hour',
      bezel_material: 'Oystersteel',
      bezel_colors: ['Steel'],
      movement_caliber: '3187',
      power_reserve: 48,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterlock with Easylink',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'GMT/24-hour hand', 'Cyclops lens'],
      original_retail_price: 8550,
      current_market_value: 10000,
      currency: 'USD',
      rarity_score: 5,
      collectibility_notes: 'Previous generation Explorer II with cal. 3187, "Polar" white dial especially popular',
      notable_features: ['Fixed 24-hour bezel', 'Orange 24-hour hand', 'Polar white dial option'],
      description: 'The previous-generation Explorer II with calibre 3187 and the beloved "Polar" white dial option.',
    },
    {
      reference_number: '226570',
      name: 'Explorer II 42mm',
      collection: 'Explorer II',
      category: 'Sport/Adventure',
      sub_category: 'GMT',
      production_start_year: 2021,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 42.0,
      case_material: 'Oystersteel',
      case_thickness: 12.5,
      lug_width: 21.0,
      dial_colors: ['Black', 'White (Polar)'],
      dial_type: 'Lacquer',
      index_markers: 'Chromalight',
      bezel_type: 'Fixed 24-hour',
      bezel_material: 'Oystersteel',
      bezel_colors: ['Steel'],
      movement_caliber: '3285',
      power_reserve: 70,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterlock with Easylink',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'GMT/24-hour hand', 'Cyclops lens'],
      original_retail_price: 9550,
      current_market_value: 11500,
      currency: 'USD',
      rarity_score: 4,
      collectibility_notes: 'Current Explorer II with upgraded movement and 70-hour power reserve',
      notable_features: ['Calibre 3285', '70-hour power reserve', 'Redesigned bracelet', 'Orange 24-hour hand'],
      description: 'The current Explorer II 42mm with calibre 3285 movement and updated case/bracelet design.',
    },

    // SEA-DWELLER
    {
      reference_number: '126660',
      name: 'Rolex Deepsea',
      collection: 'Sea-Dweller',
      category: 'Sport/Dive',
      sub_category: 'Deep Dive',
      production_start_year: 2018,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 44.0,
      case_material: 'Oystersteel',
      case_thickness: 17.7,
      lug_width: 21.0,
      dial_colors: ['Black', 'D-Blue (gradient)'],
      dial_type: 'Lacquer',
      index_markers: 'Chromalight',
      bezel_type: 'Unidirectional rotating',
      bezel_material: 'Cerachrom',
      bezel_colors: ['Black'],
      movement_caliber: '3235',
      power_reserve: 70,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterlock with Fliplock and Divers extension',
      water_resistance: 3900,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens', 'Helium escape valve'],
      original_retail_price: 14050,
      current_market_value: 14500,
      currency: 'USD',
      rarity_score: 5,
      collectibility_notes: 'D-Blue gradient dial (James Cameron edition) is the most sought-after variant',
      notable_features: ['3,900m water resistance', 'Ringlock System', 'D-Blue gradient dial', 'Helium escape valve'],
      description: 'The Rolex Deepsea rated to 3,900 metres with the innovative Ringlock System case construction.',
    },
    {
      reference_number: '136660',
      name: 'Deepsea Challenge',
      collection: 'Sea-Dweller',
      category: 'Sport/Dive',
      sub_category: 'Ultra Deep Dive',
      production_start_year: 2022,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 50.0,
      case_material: 'RLX Titanium',
      case_thickness: 23.0,
      lug_width: 22.0,
      dial_colors: ['Black', 'Deep Blue'],
      dial_type: 'Matte',
      index_markers: 'Chromalight',
      bezel_type: 'Unidirectional rotating',
      bezel_material: 'Cerachrom',
      bezel_colors: ['Black'],
      movement_caliber: '3230',
      power_reserve: 70,
      bracelet_types: ['Oyster'],
      bracelet_material: 'RLX Titanium',
      clasp_type: 'Titanium Oysterlock with Fliplock and Divers extension',
      water_resistance: 11000,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens', 'Helium escape valve'],
      original_retail_price: 26000,
      current_market_value: 28000,
      currency: 'USD',
      rarity_score: 8,
      collectibility_notes: 'Rated to 11,000m - deepest dive watch ever made commercially. RLX titanium case.',
      notable_features: ['11,000m water resistance', 'RLX titanium', '50mm case', 'Ringlock System'],
      description: 'The Deepsea Challenge rated to 11,000 metres, inspired by the Mariana Trench expedition.',
    },
    {
      reference_number: '116660',
      name: 'Rolex Deepsea (Previous Gen)',
      collection: 'Sea-Dweller',
      category: 'Sport/Dive',
      sub_category: 'Deep Dive',
      production_start_year: 2008,
      production_end_year: 2018,
      is_current_production: false,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 44.0,
      case_material: 'Oystersteel',
      case_thickness: 17.7,
      lug_width: 21.0,
      dial_colors: ['Black', 'D-Blue (gradient)'],
      dial_type: 'Lacquer',
      index_markers: 'Chromalight',
      bezel_type: 'Unidirectional rotating',
      bezel_material: 'Cerachrom',
      bezel_colors: ['Black'],
      movement_caliber: '3135',
      power_reserve: 48,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterlock with Fliplock and Divers extension',
      water_resistance: 3900,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens', 'Helium escape valve'],
      original_retail_price: 12350,
      current_market_value: 13000,
      currency: 'USD',
      rarity_score: 5,
      collectibility_notes: 'Original Deepsea with cal. 3135, D-Blue "James Cameron" dial released 2014',
      notable_features: ['3,900m water resistance', 'Ringlock System', 'Cal. 3135', 'D-Blue dial from 2014'],
      description: 'The first-generation Rolex Deepsea with calibre 3135 and the original Ringlock System.',
    },

    // YACHT-MASTER
    {
      reference_number: '226659',
      name: 'Yacht-Master 42 White Gold',
      collection: 'Yacht-Master',
      category: 'Luxury/Sport',
      sub_category: 'Regatta',
      production_start_year: 2019,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 42.0,
      case_material: '18ct White Gold',
      case_thickness: 12.1,
      lug_width: 21.0,
      dial_colors: ['Black'],
      dial_type: 'Matte',
      index_markers: 'Luminous',
      bezel_type: 'Bidirectional rotating',
      bezel_material: 'Cerachrom',
      bezel_colors: ['Matte Black'],
      movement_caliber: '3235',
      power_reserve: 70,
      bracelet_types: ['Oysterflex'],
      bracelet_material: 'Elastomer with metal blade',
      clasp_type: 'Oysterlock with Easylink',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 29700,
      current_market_value: 28000,
      currency: 'USD',
      rarity_score: 6,
      collectibility_notes: 'Largest Yacht-Master in white gold with Oysterflex strap',
      notable_features: ['42mm white gold case', 'Oysterflex bracelet', 'Cerachrom bezel'],
      description: 'The Yacht-Master 42 in 18ct white gold with Oysterflex bracelet and Cerachrom bezel.',
    },
    {
      reference_number: '116655',
      name: 'Yacht-Master 40 Everose Gold',
      collection: 'Yacht-Master',
      category: 'Luxury/Sport',
      sub_category: 'Regatta',
      production_start_year: 2015,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 40.0,
      case_material: '18ct Everose Gold',
      case_thickness: 11.9,
      lug_width: 20.0,
      dial_colors: ['Black'],
      dial_type: 'Matte',
      index_markers: 'Luminous',
      bezel_type: 'Bidirectional rotating',
      bezel_material: 'Cerachrom',
      bezel_colors: ['Matte Black'],
      movement_caliber: '3135',
      power_reserve: 48,
      bracelet_types: ['Oysterflex'],
      bracelet_material: 'Elastomer with metal blade',
      clasp_type: 'Oysterlock',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 25550,
      current_market_value: 23000,
      currency: 'USD',
      rarity_score: 5,
      collectibility_notes: 'First Rolex watch on Oysterflex bracelet, Everose gold case',
      notable_features: ['First Oysterflex bracelet', 'Everose gold case', 'Cerachrom bezel'],
      description: 'The Yacht-Master 40 in Everose gold, the first Rolex to feature the Oysterflex bracelet.',
    },
    {
      reference_number: '268655',
      name: 'Yacht-Master 37 Everose Gold',
      collection: 'Yacht-Master',
      category: 'Luxury/Sport',
      sub_category: 'Regatta',
      production_start_year: 2015,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 37.0,
      case_material: '18ct Everose Gold',
      case_thickness: 11.1,
      lug_width: 19.0,
      dial_colors: ['Black'],
      dial_type: 'Matte',
      index_markers: 'Luminous',
      bezel_type: 'Bidirectional rotating',
      bezel_material: 'Cerachrom',
      bezel_colors: ['Matte Black'],
      movement_caliber: '2236',
      power_reserve: 55,
      bracelet_types: ['Oysterflex'],
      bracelet_material: 'Elastomer with metal blade',
      clasp_type: 'Oysterlock',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 23050,
      current_market_value: 21000,
      currency: 'USD',
      rarity_score: 5,
      collectibility_notes: 'Mid-size Yacht-Master in Everose gold, unisex appeal',
      notable_features: ['37mm mid-size', 'Oysterflex bracelet', 'Syloxi hairspring'],
      description: 'The Yacht-Master 37 in Everose gold with Oysterflex bracelet and Cerachrom bezel.',
    },
    {
      reference_number: '226627',
      name: 'Yacht-Master 42 Platinum',
      collection: 'Yacht-Master',
      category: 'Luxury/Sport',
      sub_category: 'Regatta',
      production_start_year: 2023,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 42.0,
      case_material: '950 Platinum',
      case_thickness: 12.1,
      lug_width: 21.0,
      dial_colors: ['Ice Blue'],
      dial_type: 'Sunburst',
      index_markers: 'Luminous',
      bezel_type: 'Bidirectional rotating',
      bezel_material: 'Cerachrom',
      bezel_colors: ['Matte Black'],
      movement_caliber: '3235',
      power_reserve: 70,
      bracelet_types: ['Oysterflex'],
      bracelet_material: 'Elastomer with metal blade',
      clasp_type: 'Oysterlock with Easylink',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 47400,
      current_market_value: 50000,
      currency: 'USD',
      rarity_score: 8,
      collectibility_notes: 'Platinum Yacht-Master with ice blue dial, extremely exclusive',
      notable_features: ['950 Platinum case', 'Ice blue dial', 'Oysterflex bracelet', 'Cerachrom bezel'],
      description: 'The Yacht-Master 42 in 950 platinum with the signature Rolex ice blue dial.',
    },

    // OYSTER PERPETUAL
    {
      reference_number: '126000',
      name: 'Oyster Perpetual 36',
      collection: 'Oyster Perpetual',
      category: 'Classic',
      sub_category: 'Time Only',
      production_start_year: 2020,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 36.0,
      case_material: 'Oystersteel',
      case_thickness: 11.4,
      lug_width: 20.0,
      dial_colors: ['Silver', 'Blue', 'Black', 'Green', 'Yellow', 'Turquoise', 'Coral Red', 'Candy Pink'],
      dial_type: 'Lacquer',
      index_markers: 'Stick',
      bezel_type: 'Domed',
      bezel_material: 'Oystersteel',
      bezel_colors: ['Steel'],
      movement_caliber: '3230',
      power_reserve: 70,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds'],
      original_retail_price: 5800,
      current_market_value: 7500,
      currency: 'USD',
      rarity_score: 5,
      collectibility_notes: 'Vibrant colored dials created massive hype. Turquoise "Tiffany" dial especially sought after',
      notable_features: ['Celebration dial colors', 'Calibre 3230', '70-hour power reserve', 'No date clean dial'],
      description: 'The Oyster Perpetual 36 with vibrant lacquer dial colors that sparked unprecedented demand.',
    },
    {
      reference_number: '124300',
      name: 'Oyster Perpetual 41',
      collection: 'Oyster Perpetual',
      category: 'Classic',
      sub_category: 'Time Only',
      production_start_year: 2020,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 41.0,
      case_material: 'Oystersteel',
      case_thickness: 11.5,
      lug_width: 21.0,
      dial_colors: ['Silver', 'Blue', 'Black', 'Green', 'Yellow', 'Turquoise', 'Coral Red'],
      dial_type: 'Lacquer',
      index_markers: 'Stick',
      bezel_type: 'Domed',
      bezel_material: 'Oystersteel',
      bezel_colors: ['Steel'],
      movement_caliber: '3230',
      power_reserve: 70,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds'],
      original_retail_price: 5900,
      current_market_value: 8000,
      currency: 'USD',
      rarity_score: 5,
      collectibility_notes: 'Larger OP with same vibrant dial colors, Tiffany blue dial highly sought after',
      notable_features: ['41mm case', 'Celebration dial colors', 'Calibre 3230', 'No date design'],
      description: 'The Oyster Perpetual 41 offering the celebrated colorful dials in a larger case size.',
    },
    {
      reference_number: '277200',
      name: 'Oyster Perpetual 31',
      collection: 'Oyster Perpetual',
      category: 'Classic',
      sub_category: 'Time Only',
      production_start_year: 2020,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 31.0,
      case_material: 'Oystersteel',
      case_thickness: 10.8,
      lug_width: 17.0,
      dial_colors: ['Silver', 'Blue', 'Black', 'Green', 'Yellow', 'Turquoise', 'Coral Red', 'Candy Pink'],
      dial_type: 'Lacquer',
      index_markers: 'Stick',
      bezel_type: 'Domed',
      bezel_material: 'Oystersteel',
      bezel_colors: ['Steel'],
      movement_caliber: '2232',
      power_reserve: 55,
      bracelet_types: ['Oyster'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds'],
      original_retail_price: 5500,
      current_market_value: 6500,
      currency: 'USD',
      rarity_score: 4,
      collectibility_notes: 'Mid-size OP with celebration dials, popular unisex choice',
      notable_features: ['31mm mid-size', 'Celebration dials', 'Calibre 2232', 'Syloxi hairspring'],
      description: 'The Oyster Perpetual 31 with vibrant lacquer dials in a versatile mid-size case.',
    },

    // PEARLMASTER
    {
      reference_number: '86285',
      name: 'Pearlmaster 39 Everose Diamond',
      collection: 'Pearlmaster',
      category: 'Luxury/Jewelry',
      sub_category: 'Gem-set',
      production_start_year: 2012,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 39.0,
      case_material: '18ct Everose Gold',
      case_thickness: 13.0,
      lug_width: 20.0,
      dial_colors: ['Diamond-paved', 'Sundust', 'Mother of Pearl'],
      dial_type: 'Gem-set',
      index_markers: 'Diamond',
      bezel_type: 'Diamond-set',
      bezel_material: '18ct Everose Gold',
      bezel_colors: ['Everose Gold', 'Diamonds'],
      movement_caliber: '3235',
      power_reserve: 70,
      bracelet_types: ['Pearlmaster'],
      bracelet_material: '18ct Everose Gold',
      clasp_type: 'Concealed folding Crownclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 85000,
      current_market_value: 75000,
      currency: 'USD',
      rarity_score: 8,
      collectibility_notes: 'Top-tier jewelry watch with full diamond setting, extremely limited availability',
      notable_features: ['Diamond-set bezel', 'Pearlmaster bracelet', 'Gem-set dial', 'Everose gold'],
      description: 'The Pearlmaster 39 in Everose gold with diamond-set bezel and dial, a haute horlogerie masterpiece.',
    },
    {
      reference_number: '81315',
      name: 'Pearlmaster 34',
      collection: 'Pearlmaster',
      category: 'Luxury/Jewelry',
      sub_category: 'Gem-set',
      production_start_year: 2010,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 34.0,
      case_material: '18ct Everose Gold',
      case_thickness: 12.0,
      lug_width: 18.0,
      dial_colors: ['Pink', 'Mother of Pearl', 'Diamond-paved'],
      dial_type: 'Gem-set',
      index_markers: 'Diamond',
      bezel_type: 'Diamond-set',
      bezel_material: '18ct Everose Gold',
      bezel_colors: ['Everose Gold', 'Diamonds'],
      movement_caliber: '2236',
      power_reserve: 55,
      bracelet_types: ['Pearlmaster'],
      bracelet_material: '18ct Everose Gold',
      clasp_type: 'Concealed folding Crownclasp',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Cyclops lens'],
      original_retail_price: 62000,
      current_market_value: 55000,
      currency: 'USD',
      rarity_score: 7,
      collectibility_notes: 'Elegant ladies jewelry watch with full diamond treatment',
      notable_features: ['Pearlmaster bracelet', 'Diamond bezel', 'Syloxi hairspring', '34mm ladies size'],
      description: 'The Pearlmaster 34 in Everose gold with diamond-set bezel, an exquisite jewelry timepiece.',
    },

    // SKY-DWELLER
    {
      reference_number: '336934',
      name: 'Sky-Dweller Oystersteel and White Gold',
      collection: 'Sky-Dweller',
      category: 'Luxury/Travel',
      sub_category: 'Annual Calendar/GMT',
      production_start_year: 2023,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 42.0,
      case_material: 'Oystersteel and White Gold',
      case_thickness: 14.1,
      lug_width: 21.0,
      dial_colors: ['Blue', 'Bright Black', 'Silver', 'Mint Green'],
      dial_type: 'Sunburst',
      index_markers: 'Applied',
      bezel_type: 'Fluted (Command bezel)',
      bezel_material: '18ct White Gold',
      bezel_colors: ['White Gold'],
      movement_caliber: '9002',
      power_reserve: 72,
      bracelet_types: ['Oyster', 'Jubilee'],
      bracelet_material: 'Oystersteel',
      clasp_type: 'Oysterclasp with Easylink',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Month', 'Dual time zone', 'Annual calendar', '24-hour display'],
      original_retail_price: 15550,
      current_market_value: 22000,
      currency: 'USD',
      rarity_score: 7,
      collectibility_notes: 'Most accessible Sky-Dweller with new calibre 9002 and updated aesthetics',
      notable_features: ['Calibre 9002', 'Annual calendar', 'Command bezel', 'Dual time zone'],
      description: 'The Sky-Dweller in Oystersteel with white gold fluted Command bezel and updated calibre 9002.',
    },
    {
      reference_number: '326238',
      name: 'Sky-Dweller Yellow Gold',
      collection: 'Sky-Dweller',
      category: 'Luxury/Travel',
      sub_category: 'Annual Calendar/GMT',
      production_start_year: 2017,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 42.0,
      case_material: '18ct Yellow Gold',
      case_thickness: 14.1,
      lug_width: 21.0,
      dial_colors: ['Champagne', 'White', 'Black'],
      dial_type: 'Sunburst',
      index_markers: 'Applied',
      bezel_type: 'Fluted (Command bezel)',
      bezel_material: '18ct Yellow Gold',
      bezel_colors: ['Yellow Gold'],
      movement_caliber: '9001',
      power_reserve: 72,
      bracelet_types: ['Oysterflex'],
      bracelet_material: 'Elastomer with metal blade',
      clasp_type: 'Oysterlock',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Month', 'Dual time zone', 'Annual calendar', '24-hour display'],
      original_retail_price: 45450,
      current_market_value: 44000,
      currency: 'USD',
      rarity_score: 6,
      collectibility_notes: 'Full gold Sky-Dweller on Oysterflex, most complicated Rolex movement',
      notable_features: ['Calibre 9001', 'Annual calendar', 'Command bezel', 'Oysterflex bracelet'],
      description: 'The Sky-Dweller in 18ct yellow gold with Oysterflex bracelet, featuring Rolex\'s most complex movement.',
    },
    {
      reference_number: '326135',
      name: 'Sky-Dweller Everose Gold',
      collection: 'Sky-Dweller',
      category: 'Luxury/Travel',
      sub_category: 'Annual Calendar/GMT',
      production_start_year: 2017,
      production_end_year: null,
      is_current_production: true,
      is_limited_edition: false,
      limited_edition_quantity: null,
      case_size: 42.0,
      case_material: '18ct Everose Gold',
      case_thickness: 14.1,
      lug_width: 21.0,
      dial_colors: ['Sundust', 'Chocolate', 'Dark Rhodium'],
      dial_type: 'Sunburst',
      index_markers: 'Applied',
      bezel_type: 'Fluted (Command bezel)',
      bezel_material: '18ct Everose Gold',
      bezel_colors: ['Everose Gold'],
      movement_caliber: '9001',
      power_reserve: 72,
      bracelet_types: ['Oysterflex'],
      bracelet_material: 'Elastomer with metal blade',
      clasp_type: 'Oysterlock',
      water_resistance: 100,
      functions: ['Hours', 'Minutes', 'Seconds', 'Date', 'Month', 'Dual time zone', 'Annual calendar', '24-hour display'],
      original_retail_price: 44250,
      current_market_value: 43000,
      currency: 'USD',
      rarity_score: 6,
      collectibility_notes: 'Everose gold Sky-Dweller with warm tones and Oysterflex',
      notable_features: ['Calibre 9001', 'Annual calendar', 'Command bezel', 'Everose gold case'],
      description: 'The Sky-Dweller in 18ct Everose gold with Oysterflex bracelet and Command bezel.',
    },
  ];

  const insertQuery = `
    INSERT INTO rolex_models (
      reference_number, name, collection, category, sub_category,
      production_start_year, production_end_year, is_current_production,
      is_limited_edition, limited_edition_quantity,
      case_size, case_material, case_thickness, lug_width,
      dial_colors, dial_type, index_markers, bezel_type, bezel_material, bezel_colors,
      movement_caliber, power_reserve, bracelet_types, bracelet_material, clasp_type,
      water_resistance, functions,
      original_retail_price, current_market_value, currency,
      rarity_score, collectibility_notes, notable_features, description
    ) VALUES (
      $1, $2, $3, $4, $5,
      $6, $7, $8,
      $9, $10,
      $11, $12, $13, $14,
      $15, $16, $17, $18, $19, $20,
      $21, $22, $23, $24, $25,
      $26, $27,
      $28, $29, $30,
      $31, $32, $33, $34
    ) ON CONFLICT (reference_number) DO NOTHING
  `;

  let inserted = 0;
  let skipped = 0;

  for (const model of models) {
    try {
      const result = await pool.query(insertQuery, [
        model.reference_number,
        model.name,
        model.collection,
        model.category,
        model.sub_category,
        model.production_start_year,
        model.production_end_year,
        model.is_current_production,
        model.is_limited_edition,
        model.limited_edition_quantity,
        model.case_size,
        model.case_material,
        model.case_thickness,
        model.lug_width,
        model.dial_colors,
        model.dial_type,
        model.index_markers,
        model.bezel_type,
        model.bezel_material,
        model.bezel_colors,
        model.movement_caliber,
        model.power_reserve,
        model.bracelet_types,
        model.bracelet_material,
        model.clasp_type,
        model.water_resistance,
        model.functions,
        model.original_retail_price,
        model.current_market_value,
        model.currency,
        model.rarity_score,
        model.collectibility_notes,
        model.notable_features,
        model.description,
      ]);

      if (result.rowCount && result.rowCount > 0) {
        inserted++;
        console.log(`  ✅ Inserted: ${model.reference_number} - ${model.name}`);
      } else {
        skipped++;
        console.log(`  ⏭️ Skipped (already exists): ${model.reference_number} - ${model.name}`);
      }
    } catch (error: any) {
      console.error(`  ❌ Error inserting ${model.reference_number}: ${error.message}`);
    }
  }

  console.log(`\n🕰️ Rolex seed complete: ${inserted} inserted, ${skipped} skipped, ${models.length} total`);
  await pool.end();
  process.exit(0);
}

seedNewRolexModels().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
