import { db } from "./db";
import { listedBusinesses } from "@shared/schema";
import { count, and, eq } from "drizzle-orm";

export async function seedListedBusinesses() {
  const [result] = await db.select({ total: count() }).from(listedBusinesses);

  const businesses = [
    { name: 'Anchorage Pawn Shop', address: '4015 Mountain View Dr', city: 'Anchorage', state: 'AK', zip: '99508', phone: '(907) 277-2898', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 145, simpletonVerified: false },
    { name: 'National Pawn Birmingham', address: '1920 Center Point Pkwy', city: 'Birmingham', state: 'AL', zip: '35215', phone: '(205) 856-5700', website: 'nationalpawnbirmingham.com', hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 185, simpletonVerified: false },
    { name: 'Braswell & Son Pawn Brokers', address: '8302 Baseline Rd', city: 'Little Rock', state: 'AR', zip: '72209', phone: '(501) 562-9328', website: null, hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '5.0', googleReviewCount: 1441, simpletonVerified: false },
    { name: 'iPawn / Braswell & Son', address: '11108 N Rodney Parham Rd', city: 'Little Rock', state: 'AR', zip: '72212', phone: '(501) 562-5626', website: null, hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.9', googleReviewCount: 1495, simpletonVerified: false },
    { name: 'Mo Money Pawn Shop', address: '1152 E Indian School Rd', city: 'Phoenix', state: 'AZ', zip: '85014', phone: '(602) 279-4417', website: 'momoneypawn.com', hours: 'Mon-Sun: 10am-7pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 425, simpletonVerified: false },
    { name: 'Phoenix Pawn & Gold', address: '2803 W Van Buren St', city: 'Phoenix', state: 'AZ', zip: '85009', phone: '(602) 272-3449', website: 'phoenixpawnandgold.com', hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 350, simpletonVerified: false },
    { name: 'A Plus A Pawn', address: '186 S Alvarado St', city: 'Los Angeles', state: 'CA', zip: '90057', phone: '(213) 484-5414', website: 'aplusapawnshop.com', hours: 'Mon-Sat: 8am-7pm, Sun: 8am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 186, simpletonVerified: false },
    { name: 'King\'s Jewelry & Loan', address: '800 S Vermont Ave', city: 'Los Angeles', state: 'CA', zip: '90005', phone: '(213) 383-5555', website: 'kingspawn.com', hours: 'Mon-Sat: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 175, simpletonVerified: false },
    { name: 'LA Top Pawn Shop', address: '4119 Beverly Blvd', city: 'Los Angeles', state: 'CA', zip: '90004', phone: '(323) 913-0393', website: null, hours: 'Mon-Fri: 10:30am-6:30pm, Sat: 10:30am-6pm, Sun: 11am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 145, simpletonVerified: false },
    { name: 'Mr. Steve\'s Pawn Shop', address: '3800 S Western Ave', city: 'Los Angeles', state: 'CA', zip: '90062', phone: '(323) 735-0110', website: null, hours: 'Mon-Sun: 9am-12am', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 850, simpletonVerified: false },
    { name: 'Santa Monica Jewelry & Loan', address: '408 Broadway', city: 'Santa Monica', state: 'CA', zip: '90401', phone: '(310) 451-2840', website: 'santamonicajewelryandloan.com', hours: 'Mon-Sun: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 532, simpletonVerified: false },
    { name: 'Aurora Gold Pawn', address: '8030 E Mississippi Ave', city: 'Denver', state: 'CO', zip: '80247', phone: '(303) 750-5599', website: null, hours: 'Mon-Sat: 9am-6pm, Sun: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 245, simpletonVerified: false },
    { name: 'Big Daddy\'s Jewelry and Pawn', address: '2201 N Broadway', city: 'Denver', state: 'CO', zip: '80205', phone: '(303) 297-2274', website: 'bigdaddyspawndenver.com', hours: 'Mon-Fri: 9am-6pm, Sat: 9am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 310, simpletonVerified: false },
    { name: 'Hat City Pawn - Danbury', address: '17 Federal Rd', city: 'Danbury', state: 'CT', zip: '06810', phone: '(203) 748-2274', website: 'hatcitypawn.com', hours: 'Mon-Sat: 9:30am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 165, simpletonVerified: false },
    { name: 'King Cash Pawn & Jewelry', address: '1717 W Flagler St', city: 'Miami', state: 'FL', zip: '33135', phone: '(305) 649-7740', website: 'kingcashpawn.com', hours: 'Mon-Sat: 9am-7pm, Sun: 10am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 380, simpletonVerified: false },
    { name: 'La Familia Pawn and Jewelry', address: '1823 NW 79th St', city: 'Miami', state: 'FL', zip: '33147', phone: '(305) 691-3701', website: 'lafamiliapawn.com', hours: 'Mon-Fri: 9am-7pm, Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 425, simpletonVerified: false },
    { name: 'Queen of Pawns', address: '2430 NW 36th St', city: 'Miami', state: 'FL', zip: '33142', phone: '(305) 635-2225', website: 'queenofpawns.com', hours: 'Mon-Sat: 9am-7pm, Sun: 10:30am-3:30pm', category: 'pawn_shop', status: 'approved', googleRating: '4.4', googleReviewCount: 290, simpletonVerified: false },
    { name: 'The Pawn Shop Miami', address: '1038 NW 36th St', city: 'Miami', state: 'FL', zip: '33127', phone: '(305) 447-7174', website: null, hours: 'Mon-Fri: 10am-8pm, Sat: 10am-7pm', category: 'pawn_shop', status: 'approved', googleRating: '4.3', googleReviewCount: 210, simpletonVerified: false },
    { name: 'Ala Moana Pawn Shop', address: '550B Piikoi St', city: 'Honolulu', state: 'HI', zip: '96814', phone: '(808) 596-7787', website: null, hours: 'Mon-Sat: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 280, simpletonVerified: false },
    { name: 'A Quality Pawn & Jewelry', address: '1135 Army Post Rd', city: 'Des Moines', state: 'IA', zip: '50315', phone: '(515) 953-4680', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 120, simpletonVerified: false },
    { name: 'Idaho Pawn & Gold', address: '10250 W Fairview Ave', city: 'Boise', state: 'ID', zip: '83704', phone: '(208) 615-8714', website: 'pawnidaho.com', hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 185, simpletonVerified: false },
    { name: 'Sterling & Knight Jewelry & Pawn', address: '295 S Schmidt Rd', city: 'Bolingbrook', state: 'IL', zip: '60440', phone: '(630) 759-9100', website: 'skjewelryandpawn.com', hours: 'Mon: 10am-7pm, Tue-Fri: 10am-6pm, Sat: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.9', googleReviewCount: 6000, simpletonVerified: false },
    { name: 'Clark Pawners & Jewelers', address: '2626 N Clark St', city: 'Chicago', state: 'IL', zip: '60614', phone: '(773) 900-5522', website: null, hours: 'Mon-Fri: 9am-5:30pm, Sat: 10am-5:30pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 340, simpletonVerified: false },
    { name: 'Royal Pawn Shop', address: '428 S Clark St', city: 'Chicago', state: 'IL', zip: '60605', phone: '(312) 427-6542', website: null, hours: 'Mon-Fri: 9am-6pm, Sat: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 290, simpletonVerified: false },
    { name: 'Dock Brothers Jewelry & Loan', address: '2464 N Meridian St', city: 'Indianapolis', state: 'IN', zip: '46208', phone: '(317) 926-6006', website: 'dockbros.com', hours: 'Mon-Fri: 10am-5pm, Sat: 10am-1pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 260, simpletonVerified: false },
    { name: 'Uncle Miltie\'s Pawn Shop', address: '3775 Southern Pkwy', city: 'Louisville', state: 'KY', zip: '40214', phone: '(502) 364-8844', website: null, hours: 'Mon-Fri: 10am-6pm, Sat: 10am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 210, simpletonVerified: false },
    { name: 'Magazine Pawn Shop', address: '3315 Magazine St', city: 'New Orleans', state: 'LA', zip: '70115', phone: '(504) 891-1332', website: 'magazinepawn.com', hours: 'Mon-Sat: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 175, simpletonVerified: false },
    { name: 'Empire Loan Boston', address: '1130 Washington St', city: 'Boston', state: 'MA', zip: '02118', phone: '(617) 423-9366', website: 'empireloan.com', hours: 'Tue-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 310, simpletonVerified: false },
    { name: 'Suffolk Jewelers & Pawnbrokers', address: '240 Meridian St', city: 'Boston', state: 'MA', zip: '02128', phone: '(617) 567-9000', website: null, hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 195, simpletonVerified: false },
    { name: 'USA Pawn Maryland', address: '6625 Baltimore National Pike', city: 'Baltimore', state: 'MD', zip: '21228', phone: '(410) 747-0505', website: null, hours: 'Mon-Sat: 9am-7pm, Sun: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.4', googleReviewCount: 165, simpletonVerified: false },
    { name: 'Fast Cash Battle Creek', address: '641 Capital Ave SW', city: 'Battle Creek', state: 'MI', zip: '49015', phone: '(269) 966-0079', website: null, hours: 'Mon-Fri: 10am-6pm, Sat: 10am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.3', googleReviewCount: 85, simpletonVerified: false },
    { name: 'Bay City Discount', address: '715 Washington Ave', city: 'Bay City', state: 'MI', zip: '48708', phone: '(989) 893-6649', website: null, hours: 'Tue-Fri: 9am-6pm, Sat: 9:30am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 145, simpletonVerified: false },
    { name: 'Canton Jewelry & Pawn', address: '41637 Ford Rd', city: 'Canton', state: 'MI', zip: '48187', phone: '(734) 844-0893', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.4', googleReviewCount: 95, simpletonVerified: false },
    { name: 'US Pawn Jewelry & Loan', address: '4845 S Beech Daly St', city: 'Dearborn Heights', state: 'MI', zip: '48125', phone: '(313) 908-2787', website: null, hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.4', googleReviewCount: 145, simpletonVerified: false },
    { name: 'American Jewelry & Loan', address: '20450 Greenfield Rd', city: 'Detroit', state: 'MI', zip: '48235', phone: '(313) 345-4000', website: 'pawndetroit.com', hours: 'Mon-Sat: 9:30am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 2800, simpletonVerified: false },
    { name: 'Motor City Pawn Brokers - Detroit', address: '15440 E 8 Mile Rd', city: 'Detroit', state: 'MI', zip: '48205', phone: '(313) 371-8201', website: 'motorcitypawnbrokers.com', hours: 'Mon-Fri: 9am-6pm, Sat: 9am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 340, simpletonVerified: true },
    { name: 'Zeidman\'s Pawn and Loan', address: '2669 Gratiot Ave', city: 'Detroit', state: 'MI', zip: '48207', phone: '(313) 567-7170', website: 'zeidmanspawnandloan.com', hours: 'Mon-Fri: 9am-5pm, Sat: 9am-3pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 420, simpletonVerified: false },
    { name: 'Motor City Pawn Brokers - Ferndale', address: '1461 E 8 Mile Rd', city: 'Ferndale', state: 'MI', zip: '48220', phone: '(248) 439-0950', website: 'motorcitypawnbrokers.com', hours: 'Mon-Fri: 9am-6pm, Sat: 9am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 425, simpletonVerified: true },
    { name: 'Mega Pawn #1', address: '3825 Corunna Rd', city: 'Flint', state: 'MI', zip: '48532', phone: '(810) 235-1900', website: 'megapawnstores.com', hours: 'Mon-Fri: 9:30am-6pm, Sat: 10am-3pm', category: 'pawn_shop', status: 'approved', googleRating: '4.2', googleReviewCount: 120, simpletonVerified: false },
    { name: 'Mega Pawn #4', address: 'G-3070 Miller Rd', city: 'Flint', state: 'MI', zip: '48507', phone: '(810) 234-8800', website: 'megapawnstores.com', hours: 'Mon-Fri: 9:30am-6pm, Sat: 10am-3pm', category: 'pawn_shop', status: 'approved', googleRating: '4.4', googleReviewCount: 145, simpletonVerified: false },
    { name: 'Motor City Pawn Brokers - Hamtramck', address: '2673 Caniff St', city: 'Hamtramck', state: 'MI', zip: '48212', phone: '(313) 855-0004', website: 'motorcitypawnbrokers.com', hours: 'Mon-Fri: 9am-6pm, Sat: 9am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 210, simpletonVerified: true },
    { name: 'American Jewelry & Loan - Hazel Park', address: '23123 John R Rd', city: 'Hazel Park', state: 'MI', zip: '48030', phone: '(248) 544-3300', website: 'pawndetroit.com', hours: 'Mon-Sat: 9:30am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 380, simpletonVerified: false },
    { name: 'Action Discount', address: '625 Shirley Dr', city: 'Jackson', state: 'MI', zip: '49202', phone: '(517) 787-4944', website: null, hours: 'Mon-Fri: 9am-5pm, Sat: 9am-4:30pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 48, simpletonVerified: false },
    { name: 'Dicker & Deal Jackson', address: '209 S Mechanic St', city: 'Jackson', state: 'MI', zip: '49201', phone: '(517) 783-3325', website: 'dickeranddeal.com', hours: 'Daily: 10am-5:30pm', category: 'pawn_shop', status: 'approved', googleRating: '4.4', googleReviewCount: 95, simpletonVerified: false },
    { name: 'Fast Cash Outlet', address: '939 E Cork St', city: 'Kalamazoo', state: 'MI', zip: '49001', phone: '(269) 552-4301', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.3', googleReviewCount: 110, simpletonVerified: false },
    { name: 'TNT Pawnbrokers', address: '3938 S Westnedge Ave', city: 'Kalamazoo', state: 'MI', zip: '49008', phone: '(269) 384-0008', website: 'tntpawnbrokers.com', hours: 'Mon-Fri: 10am-6pm, Sat: 10am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 230, simpletonVerified: false },
    { name: 'Best Deal Pawn', address: '4622 1/2 S Cedar St', city: 'Lansing', state: 'MI', zip: '48910', phone: '(517) 887-2700', website: null, hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.4', googleReviewCount: 120, simpletonVerified: false },
    { name: 'Capitol Discount & Second Hand', address: '5724 S Martin Luther King Jr Blvd', city: 'Lansing', state: 'MI', zip: '48911', phone: '(517) 393-9800', website: null, hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.3', googleReviewCount: 155, simpletonVerified: false },
    { name: 'Dicker & Deal', address: '2408 S Cedar St', city: 'Lansing', state: 'MI', zip: '48910', phone: '(517) 487-3886', website: 'dickeranddeal.com', hours: 'Mon-Sat: 9am-6pm, Sun: 12pm-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 210, simpletonVerified: false },
    { name: 'Great Lakes Pawn', address: '27675 Grand River Ave', city: 'Livonia', state: 'MI', zip: '48152', phone: '(248) 987-6230', website: 'greatlakespawn.com', hours: 'Mon-Fri: 9am-6pm, Sat: 9am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 195, simpletonVerified: false },
    { name: 'Livonia Pawn & Jewelry', address: '15230 Middlebelt Rd', city: 'Livonia', state: 'MI', zip: '48154', phone: '(734) 513-2030', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 120, simpletonVerified: false },
    { name: 'Quick Cash & Guns', address: '2612 US Highway 41 W', city: 'Marquette', state: 'MI', zip: '49855', phone: '(906) 273-0669', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.3', googleReviewCount: 75, simpletonVerified: false },
    { name: 'Gold-N-Stones II Pawn Shop', address: '177 N Gratiot Ave', city: 'Mount Clemens', state: 'MI', zip: '48043', phone: '(586) 468-7060', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.4', googleReviewCount: 110, simpletonVerified: false },
    { name: 'Cash Money Pawn Shop', address: '986 Pine St', city: 'Muskegon', state: 'MI', zip: '49442', phone: '(231) 830-6575', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.3', googleReviewCount: 85, simpletonVerified: false },
    { name: 'American Jewelry & Loan - Pontiac', address: '546 N Telegraph Rd', city: 'Pontiac', state: 'MI', zip: '48341', phone: '(248) 409-5626', website: 'pawndetroit.com', hours: 'Mon-Sat: 9:30am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 431, simpletonVerified: false },
    { name: 'The Hock Shop & Sporting Center', address: '1508 Military St', city: 'Port Huron', state: 'MI', zip: '48060', phone: '(810) 985-4082', website: 'thehockshop.net', hours: 'Mon-Sat: 9am-6pm, Sun: 10am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 165, simpletonVerified: false },
    { name: 'Motor City Pawn Brokers - Roseville', address: '26510 Gratiot Ave', city: 'Roseville', state: 'MI', zip: '48066', phone: '(586) 772-2274', website: 'motorcitypawnbrokers.com', hours: 'Mon-Fri: 10am-7pm, Sat: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 315, simpletonVerified: true },
    { name: 'Westside Discount', address: '1014 Gratiot Ave', city: 'Saginaw', state: 'MI', zip: '48602', phone: '(989) 921-2222', website: null, hours: 'Mon-Fri: 9am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.4', googleReviewCount: 110, simpletonVerified: false },
    { name: '14K Pawn & Exchange', address: '24810 Evergreen Rd', city: 'Southfield', state: 'MI', zip: '48075', phone: '(248) 440-5760', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 175, simpletonVerified: false },
    { name: 'Lew Silver Diamond Broker', address: '15631 W 9 Mile Rd', city: 'Southfield', state: 'MI', zip: '48075', phone: '(248) 559-5323', website: null, hours: 'Mon-Fri: 10am-5pm, Sat: 10am-3pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 160, simpletonVerified: false },
    { name: 'Norman\'s Jewelry & Loan', address: '24777 Telegraph Rd Ste B', city: 'Southfield', state: 'MI', zip: '48033', phone: '(248) 356-8850', website: null, hours: 'Mon-Fri: 10am-6pm, Sat: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 285, simpletonVerified: false },
    { name: 'American Jewelry & Loan - Southgate', address: '14336 Eureka Rd', city: 'Southgate', state: 'MI', zip: '48195', phone: '(734) 225-6811', website: 'pawndetroit.com', hours: 'Mon-Sat: 9:30am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 310, simpletonVerified: false },
    { name: 'ACE Buyers', address: '1396 W S Airport Rd', city: 'Traverse City', state: 'MI', zip: '49686', phone: '(231) 929-3344', website: null, hours: 'Mon-Fri: 9am-6pm, Sat: 9am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 125, simpletonVerified: false },
    { name: 'Check N Gold', address: '27183 Van Dyke Ave', city: 'Warren', state: 'MI', zip: '48093', phone: '(586) 427-5434', website: null, hours: 'Mon-Sat: 9am-7pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 195, simpletonVerified: false },
    { name: 'Eight Mile Pawn Brokers', address: '7657 E 8 Mile Rd', city: 'Warren', state: 'MI', zip: '48091', phone: '(586) 755-2274', website: null, hours: 'Mon-Fri: 10am-7pm, Sat: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 210, simpletonVerified: false },
    { name: 'Motor City Pawn Brokers', address: '22100 Van Dyke Ave', city: 'Warren', state: 'MI', zip: '48089', phone: '(586) 758-2274', website: 'motorcitypawnbrokers.com', hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.9', googleReviewCount: 698, simpletonVerified: true },
    { name: 'Wyandotte Gold Exchange', address: '3170 Biddle Ave', city: 'Wyandotte', state: 'MI', zip: '48192', phone: '(734) 282-4200', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 110, simpletonVerified: false },
    { name: '14K Gold & Coin', address: '1518 Washtenaw Rd', city: 'Ypsilanti', state: 'MI', zip: '48197', phone: '(734) 487-6666', website: null, hours: 'Mon-Fri: 9am-6pm, Sat: 9am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 175, simpletonVerified: false },
    { name: '3D Gold and Merchandise Brokers', address: '1701 E Michigan Ave', city: 'Ypsilanti', state: 'MI', zip: '48198', phone: '(734) 481-1776', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.3', googleReviewCount: 95, simpletonVerified: false },
    { name: 'Bondy\'s Gold & Shoppe', address: '1779 Washtenaw Rd', city: 'Ypsilanti', state: 'MI', zip: '48197', phone: '(734) 544-1218', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 130, simpletonVerified: false },
    { name: 'Uptown Pawn', address: '301 W Lake St', city: 'Minneapolis', state: 'MN', zip: '55408', phone: '(612) 823-3001', website: null, hours: 'Mon-Sat: 10am-6pm, Sun: 12pm-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 195, simpletonVerified: false },
    { name: 'Sol\'s Jewelry & Pawn KC', address: '721 State Ave', city: 'Kansas City', state: 'KS', zip: '66101', phone: '(913) 371-4043', website: 'solskc.com', hours: 'Mon-Fri: 9:30am-5:30pm, Sat: 10am-3pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 175, simpletonVerified: false },
    { name: 'Cash America Pawn', address: '2875 Greenville Bypass', city: 'Greenville', state: 'MS', zip: '38703', phone: '(662) 335-8100', website: null, hours: 'Mon-Sat: 9am-7pm', category: 'pawn_shop', status: 'approved', googleRating: '4.3', googleReviewCount: 145, simpletonVerified: false },
    { name: 'National Pawn and Jewelry', address: '5700 South Blvd', city: 'Charlotte', state: 'NC', zip: '28217', phone: '(704) 469-4554', website: 'nationalpawnshops.com', hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 280, simpletonVerified: false },
    { name: 'Dakota Pawn', address: '221 N 4th St', city: 'Bismarck', state: 'ND', zip: '58501', phone: '(701) 223-5865', website: null, hours: 'Mon-Fri: 9am-6pm, Sat: 10am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.4', googleReviewCount: 85, simpletonVerified: false },
    { name: 'H. Schoenberg Pawnbrokers', address: '744 Bergen Ave', city: 'Jersey City', state: 'NJ', zip: '07306', phone: '(201) 653-2020', website: 'jerseycitypawnshop.com', hours: 'Mon-Fri: 9am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 185, simpletonVerified: false },
    { name: 'William S. Rich & Son', address: '857 Broad St', city: 'Newark', state: 'NJ', zip: '07102', phone: '(973) 623-1616', website: 'wmsrichandson.com', hours: 'Mon-Sat: 9am-5:30pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 340, simpletonVerified: false },
    { name: 'Uptown Pawn Albuquerque', address: '10300 Menaul Blvd NE Suite 18', city: 'Albuquerque', state: 'NM', zip: '87112', phone: '(505) 293-1863', website: null, hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 195, simpletonVerified: false },
    { name: 'Gold & Silver Pawn Shop', address: '713 S Las Vegas Blvd', city: 'Las Vegas', state: 'NV', zip: '89101', phone: '(702) 385-7912', website: 'gspawn.com', hours: 'Mon-Sun: 10am-5:30pm, 24hr pawn window', category: 'pawn_shop', status: 'approved', googleRating: '4.4', googleReviewCount: 15200, simpletonVerified: false },
    { name: 'GEM Pawnbrokers - Flatbush', address: '230 Flatbush Ave', city: 'Brooklyn', state: 'NY', zip: '11217', phone: '(718) 596-5626', website: 'gempawnbrokers.com', hours: 'Mon-Wed, Fri-Sat: 9am-6pm, Thu: 9am-7pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 456, simpletonVerified: false },
    { name: 'GEM Pawnbrokers - Flatbush Ave', address: '1535 Flatbush Ave', city: 'Brooklyn', state: 'NY', zip: '11210', phone: '(718) 421-0033', website: 'gempawnbrokers.com', hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 320, simpletonVerified: false },
    { name: 'Lincoln Square Pawnbrokers', address: '724 Amsterdam Ave', city: 'New York', state: 'NY', zip: '10025', phone: '(212) 865-8860', website: 'lincolnsquarepawn.com', hours: 'Mon-Fri: 9am-5pm, Sat: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 76, simpletonVerified: false },
    { name: 'Dash 2 Cash Pawn Shop', address: '1253 Morse Rd', city: 'Columbus', state: 'OH', zip: '43229', phone: '(614) 817-1190', website: 'dash2cashpawnshop.com', hours: 'Mon-Thu: 10am-7pm, Fri-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '5.0', googleReviewCount: 75, simpletonVerified: false },
    { name: 'Gemco Coins Jewelry & Pawn', address: '5311 W Broad St', city: 'Columbus', state: 'OH', zip: '43228', phone: '(614) 878-2646', website: 'gemcocoins.com', hours: 'Mon-Sat: 9:30am-5:30pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 190, simpletonVerified: false },
    { name: 'Neighborhood Pawn', address: '2421 SW 29th St', city: 'Oklahoma City', state: 'OK', zip: '73119', phone: '(405) 604-8001', website: null, hours: 'Mon-Fri: 9am-7pm, Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.9', googleReviewCount: 340, simpletonVerified: false },
    { name: 'A-1 Hawk Inc', address: '12314 SE Division St', city: 'Portland', state: 'OR', zip: '97236', phone: '(503) 760-0700', website: 'a1hawk.com', hours: 'Mon-Sat: 10am-6pm, Sun: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 310, simpletonVerified: false },
    { name: 'All That Glitters', address: '12200 SE Division St', city: 'Portland', state: 'OR', zip: '97236', phone: '(503) 761-9699', website: null, hours: 'Mon-Sat: 10am-7pm, Sun: 11am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 240, simpletonVerified: false },
    { name: 'Tigard Pawn 4 More', address: '11940 SW Pacific Hwy Suite A', city: 'Tigard', state: 'OR', zip: '97223', phone: '(503) 624-7800', website: null, hours: 'Mon-Fri: 10am-6:30pm, Sat: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.9', googleReviewCount: 185, simpletonVerified: false },
    { name: 'Carver W Reed & Co', address: '121 S 10th St', city: 'Philadelphia', state: 'PA', zip: '19107', phone: '(215) 923-1443', website: null, hours: 'Mon-Fri: 10am-5pm, Sat: 10am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 185, simpletonVerified: false },
    { name: 'Forman\'s Pawn PA', address: '626 S 12th St', city: 'Philadelphia', state: 'PA', zip: '19147', phone: '(215) 735-3073', website: null, hours: 'Mon-Fri: 9am-5pm, Sat: 9am-3pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 310, simpletonVerified: false },
    { name: 'Providence Pawnbrokers', address: '1405 Broad St', city: 'Providence', state: 'RI', zip: '02905', phone: '(401) 461-6337', website: null, hours: 'Mon-Sat: 9am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 120, simpletonVerified: false },
    { name: 'Diamond Banc Nashville', address: '3805 Green Hills Village Dr', city: 'Nashville', state: 'TN', zip: '37215', phone: '(615) 695-7675', website: 'diamondbanc.com', hours: 'Mon-Fri: 10am-5pm, Sat: By Appt', category: 'pawn_shop', status: 'approved', googleRating: '4.9', googleReviewCount: 165, simpletonVerified: false },
    { name: 'Easy Pawn Nashville', address: '2915 Dickerson Pike', city: 'Nashville', state: 'TN', zip: '37207', phone: '(615) 227-2854', website: null, hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 220, simpletonVerified: false },
    { name: 'Uncle Dan\'s Pawn - East Dallas', address: '5404 E Grand Ave', city: 'Dallas', state: 'TX', zip: '75223', phone: '(214) 823-8750', website: 'uncledanspawn.com', hours: 'Mon-Fri: 10am-7pm, Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 290, simpletonVerified: false },
    { name: 'EZPAWN Hillcroft', address: '6761 Hillcroft St', city: 'Houston', state: 'TX', zip: '77081', phone: '(713) 988-2262', website: 'ezpawn.com', hours: 'Mon-Sat: 9am-7pm', category: 'pawn_shop', status: 'approved', googleRating: '4.3', googleReviewCount: 310, simpletonVerified: false },
    { name: 'First Class Jewelry and Loan', address: '3823 Richmond Ave', city: 'Houston', state: 'TX', zip: '77027', phone: '(713) 622-7296', website: 'fcjal.com', hours: 'Mon-Fri: 10am-6pm, Sat: 11am-3pm', category: 'pawn_shop', status: 'approved', googleRating: '4.9', googleReviewCount: 380, simpletonVerified: false },
    { name: 'Harrisburg Pawn', address: '7305 Harrisburg Blvd', city: 'Houston', state: 'TX', zip: '77011', phone: '(713) 926-8892', website: null, hours: 'Mon-Sat: 9am-6pm, Sun: 10am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 245, simpletonVerified: false },
    { name: 'Wright Pawn & Jewelry', address: '6218 Westheimer Rd', city: 'Houston', state: 'TX', zip: '77057', phone: '(713) 780-2274', website: 'wrightpawnandjewelry.com', hours: 'Tue-Fri: 10am-6pm, Sat: 10am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 520, simpletonVerified: false },
    { name: 'Dallas Super Pawn', address: '580 S Belt Line Rd', city: 'Irving', state: 'TX', zip: '75060', phone: '(972) 986-1950', website: 'dallassuperpawn.com', hours: 'Mon-Fri: 9am-7pm, Sat: 9am-6pm, Sun: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 195, simpletonVerified: false },
    { name: 'Big Dog Pawn & Jewelry', address: '6610 S State St', city: 'Murray', state: 'UT', zip: '84107', phone: '(385) 800-7296', website: 'bigdogpawn.com', hours: 'Mon-Sat: 10am-7pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 260, simpletonVerified: false },
    { name: 'Crown Jewelers & Pawn', address: '130 E 3300 S', city: 'South Salt Lake', state: 'UT', zip: '84115', phone: '(801) 467-1115', website: 'pawnutah.com', hours: 'Mon-Sat: 9am-7pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 350, simpletonVerified: false },
    { name: 'The Vault Jewelry & Loan', address: '102 E Main St', city: 'Charlottesville', state: 'VA', zip: '22902', phone: '(434) 293-2200', website: 'thevaultloans.com', hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 290, simpletonVerified: false },
    { name: 'Renton Pawn Shop', address: '729 S 3rd St', city: 'Renton', state: 'WA', zip: '98057', phone: '(425) 255-4545', website: null, hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 175, simpletonVerified: false },
    { name: 'Western Pawn', address: '1703 E Lincolnway', city: 'Cheyenne', state: 'WY', zip: '82001', phone: '(307) 632-9400', website: null, hours: 'Mon-Fri: 9am-6pm, Sat: 10am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 75, simpletonVerified: false },
    { name: 'Levy\'s Pawn Shop', address: '501 N Market St', city: 'Wilmington', state: 'DE', zip: '19801', phone: '(302) 652-8352', website: 'levyspawnshop.com', hours: 'Mon-Fri: 8:30am-5:30pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 145, simpletonVerified: false },
    { name: 'Lou\'s Jewelry & Pawn', address: '712 N Market St', city: 'Wilmington', state: 'DE', zip: '19801', phone: '(302) 888-1812', website: null, hours: 'Mon-Fri: 9am-4pm, Sat: 9am-1pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 120, simpletonVerified: false },
    { name: 'Chapes-JPL', address: '3355 Lenox Rd NE Ste 875', city: 'Atlanta', state: 'GA', zip: '30326', phone: '(404) 504-7021', website: 'chapesjpl.com', hours: 'Mon-Thu: 10am-5:30pm, Fri: 10am-5pm, Sat: 10am-1pm', category: 'pawn_shop', status: 'approved', googleRating: '4.9', googleReviewCount: 520, simpletonVerified: false },
    { name: 'Dynasty Jewelry and Loan', address: '5075 Jimmy Carter Blvd', city: 'Norcross', state: 'GA', zip: '30093', phone: '(770) 300-0099', website: 'dynastypawn.com', hours: 'Mon-Fri: 9:30am-6pm, Sat: 9:30am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 380, simpletonVerified: false },
    { name: 'Coastal Trading & Pawn', address: '292 Saint John St', city: 'Portland', state: 'ME', zip: '04102', phone: '(207) 541-9046', website: 'coastaltradingandpawn.com', hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 195, simpletonVerified: false },
    { name: 'Stinson & Company', address: '337 Forest Ave', city: 'Portland', state: 'ME', zip: '04101', phone: '(207) 805-1138', website: 'stinsonandcompany.com', hours: 'Mon-Fri: 10am-5pm, Sat: 10am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 165, simpletonVerified: false },
    { name: 'J\'s Pawn & Loan', address: '1380 Brush Creek Blvd', city: 'Kansas City', state: 'MO', zip: '64110', phone: '(816) 753-5080', website: null, hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 175, simpletonVerified: false },
    { name: 'Avenue Pawn and Jewelry', address: '2706 Independence Ave', city: 'Kansas City', state: 'MO', zip: '64124', phone: '(816) 483-6767', website: null, hours: 'Mon-Fri: 9am-6:30pm, Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.4', googleReviewCount: 145, simpletonVerified: false },
    { name: 'National Pawn', address: '1416 Main St', city: 'Billings', state: 'MT', zip: '59105', phone: '(406) 281-8546', website: 'firstnationalpawn.com', hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 210, simpletonVerified: false },
    { name: 'Northwest Pawn and Gun', address: '1717 Central Ave', city: 'Billings', state: 'MT', zip: '59102', phone: '(406) 256-7871', website: 'northwestpawnandgunbillings.com', hours: 'Mon-Sat: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 155, simpletonVerified: false },
    { name: 'Sol\'s Jewelry & Loan', address: '2215 Harney St', city: 'Omaha', state: 'NE', zip: '68102', phone: '(402) 342-7764', website: 'solsomaha.com', hours: 'Mon-Sat: 9am-6pm, Sun: 11am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 450, simpletonVerified: false },
    { name: 'EZ Money Pawn and Jewelry', address: '4721 S 24th St', city: 'Omaha', state: 'NE', zip: '68107', phone: '(402) 731-8344', website: 'ezmoneyomaha.com', hours: 'Mon-Fri: 9am-6pm, Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 185, simpletonVerified: false },
    { name: 'US Gold & Pawn', address: '890 S Willow St #2', city: 'Manchester', state: 'NH', zip: '03103', phone: '(603) 300-8888', website: 'usgoldandpawn.com', hours: 'Mon-Thu: 10am-6pm, Fri: 9am-5pm, Sat: 9am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 130, simpletonVerified: false },
    { name: 'Manchester Pawn', address: '361 Elm St', city: 'Manchester', state: 'NH', zip: '03101', phone: '(603) 622-7296', website: 'manchesterpawnonline.com', hours: 'Mon-Fri: 10am-6pm, Sat: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 175, simpletonVerified: false },
    { name: 'Gene\'s Jewelry & Pawn', address: '5818 Rivers Ave Ste B', city: 'North Charleston', state: 'SC', zip: '29406', phone: '(843) 744-5744', website: 'genespawn.com', hours: 'Mon-Fri: 9am-6:30pm, Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 290, simpletonVerified: false },
    { name: 'LowCountry Pawn & Jewelry', address: '1738 Ashley River Rd', city: 'Charleston', state: 'SC', zip: '29407', phone: '(843) 769-5500', website: 'charlestonscpawnshops.com', hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 165, simpletonVerified: false },
    { name: 'Sunset Strip Pawn', address: '2407 W 12th St', city: 'Sioux Falls', state: 'SD', zip: '57104', phone: '(605) 334-4123', website: 'sunsetstrippawninc.com', hours: 'Mon-Sat: 9am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 195, simpletonVerified: false },
    { name: 'Great Plains Pawn', address: '1007 W 41st St', city: 'Sioux Falls', state: 'SD', zip: '57105', phone: '(605) 799-4770', website: 'greatplainspawn.com', hours: 'Mon-Sat: 10am-7pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 140, simpletonVerified: false },
    { name: 'Vermont Coin & Jewelry', address: '150 Dorset St Ste 330', city: 'South Burlington', state: 'VT', zip: '05403', phone: '(802) 985-3950', website: 'vermontcoinandjewelry.com', hours: 'Mon-Fri: 9:30am-5pm, Sat: 10am-3pm', category: 'pawn_shop', status: 'approved', googleRating: '4.8', googleReviewCount: 175, simpletonVerified: false },
    { name: 'Reflections Jewelry', address: '1306 W Forest Home Ave', city: 'Milwaukee', state: 'WI', zip: '53204', phone: '(414) 672-6108', website: 'pawnmilwaukee.com', hours: 'Mon-Fri: 10am-6pm, Sat: 10am-5pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 210, simpletonVerified: false },
    { name: 'Steins Jewelry and Loan', address: '715 W Wisconsin Ave', city: 'Milwaukee', state: 'WI', zip: '53233', phone: '(414) 272-2356', website: 'steinsjewelryandloan.com', hours: 'Mon-Fri: 9am-5:30pm, Sat: 9am-4pm', category: 'pawn_shop', status: 'approved', googleRating: '4.7', googleReviewCount: 285, simpletonVerified: false },
    { name: 'KV Jewelry and Loan', address: '7108 MacCorkle Ave SE', city: 'Charleston', state: 'WV', zip: '25304', phone: '(304) 925-9345', website: null, hours: 'Mon-Sat: 9am-9pm, Sun: 10am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.5', googleReviewCount: 175, simpletonVerified: false },
    { name: 'Will Jewelry & Loan', address: '5523 MacCorkle Ave SW', city: 'South Charleston', state: 'WV', zip: '25309', phone: '(304) 768-5101', website: null, hours: 'Mon-Sat: 9am-9pm, Sun: 11am-6pm', category: 'pawn_shop', status: 'approved', googleRating: '4.6', googleReviewCount: 195, simpletonVerified: false },
  ];

  if (result.total === 0) {
    for (const biz of businesses) {
      await db.insert(listedBusinesses).values({
        name: biz.name,
        address: biz.address,
        city: biz.city,
        state: biz.state,
        zip: biz.zip,
        phone: biz.phone,
        website: biz.website,
        hours: biz.hours,
        category: biz.category,
        status: biz.status,
        googleRating: biz.googleRating,
        googleReviewCount: biz.googleReviewCount,
        simpletonVerified: biz.simpletonVerified,
        approvalDate: biz.status === "approved" ? new Date() : null,
      });
    }
    console.log(`📋 Simpleton's List: Seeded ${businesses.length} businesses across all 50 states`);
  } else {
    let added = 0;
    let updated = 0;
    for (const biz of businesses) {
      const existingRows = await db.select({ id: listedBusinesses.id, address: listedBusinesses.address, phone: listedBusinesses.phone })
        .from(listedBusinesses)
        .where(and(eq(listedBusinesses.name, biz.name), eq(listedBusinesses.state, biz.state)));
      if (existingRows.length === 0) {
        await db.insert(listedBusinesses).values({
          name: biz.name,
          address: biz.address,
          city: biz.city,
          state: biz.state,
          zip: biz.zip,
          phone: biz.phone,
          website: biz.website,
          hours: biz.hours,
          category: biz.category,
          status: biz.status,
          googleRating: biz.googleRating,
          googleReviewCount: biz.googleReviewCount,
          simpletonVerified: biz.simpletonVerified,
          approvalDate: biz.status === "approved" ? new Date() : null,
        });
        added++;
      } else {
        const existing = existingRows[0];
        if (existing.address !== biz.address || existing.phone !== biz.phone) {
          await db.update(listedBusinesses)
            .set({
              address: biz.address,
              city: biz.city,
              zip: biz.zip,
              phone: biz.phone,
              website: biz.website,
              hours: biz.hours,
              googleRating: biz.googleRating,
              googleReviewCount: biz.googleReviewCount,
              simpletonVerified: biz.simpletonVerified,
            })
            .where(eq(listedBusinesses.id, existing.id));
          updated++;
        }
      }
    }
    const parts = [];
    if (added > 0) parts.push(`added ${added}`);
    if (updated > 0) parts.push(`updated ${updated}`);
    if (parts.length > 0) {
      console.log(`📋 Simpleton's List: ${parts.join(', ')} businesses (${result.total + added} total)`);
    } else {
      console.log(`📋 Simpleton's List: ${result.total} businesses already up to date`);
    }
  }
}
