import { useRef } from "react";
import { Printer, Download, X } from "lucide-react";

interface ProfessionalDocumentProps {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
  onClose?: () => void;
}

export function ProfessionalDocument({ title, subtitle, children, onClose }: ProfessionalDocumentProps) {
  const contentRef = useRef<HTMLDivElement>(null);

  const currentDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const buildReportHTML = () => {
    let bodyContent = '';
    if (contentRef.current) {
      const clone = contentRef.current.cloneNode(true) as HTMLElement;
      clone.querySelectorAll('button, .no-print, [data-radix]').forEach(el => el.remove());
      bodyContent = clone.innerHTML;
    }

    return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${title} — Simpleton™</title>
<style>
  @page { margin: 0.75in 0.85in; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Georgia', 'Times New Roman', serif;
    color: #222;
    background: #fff;
    line-height: 1.75;
    font-size: 13.5px;
  }

  .page { max-width: 720px; margin: 0 auto; padding: 48px 0; }

  /* ── letterhead ── */
  .letterhead {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    padding-bottom: 18px;
    border-bottom: 2.5px solid #c9a96e;
    margin-bottom: 32px;
  }
  .lh-left { display: flex; align-items: center; gap: 14px; }
  .lh-left img { width: 52px; height: 52px; border-radius: 6px; object-fit: contain; }
  .lh-name { font-size: 21px; font-weight: 700; color: #c9a96e; letter-spacing: -0.01em; }
  .lh-tag  { font-size: 10px; text-transform: uppercase; letter-spacing: 0.14em; color: #999; margin-top: 1px; }
  .lh-right { text-align: right; font-size: 11px; color: #999; line-height: 1.5; }

  /* ── title block ── */
  .title-block { margin-bottom: 28px; }
  .title-block h1 { font-size: 19px; font-weight: 700; color: #1a1a1a; margin-bottom: 2px; }
  .title-block .sub { font-size: 12.5px; color: #888; }

  /* ── report body ── */
  .report-body {
    font-size: 13.5px;
    line-height: 1.8;
    color: #333;
  }
  .report-body p { margin-bottom: 14px; text-align: justify; }
  .report-body p:last-child { margin-bottom: 0; }

  /* ── footer ── */
  .report-footer {
    margin-top: 44px;
    padding-top: 14px;
    border-top: 1px solid #e0dbd3;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }
  .disclaimer { font-size: 8.5px; color: #aaa; max-width: 78%; line-height: 1.5; }
  .brand { font-size: 9.5px; font-weight: 600; color: #c9a96e; }

  @media print {
    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .page { padding: 0; }
  }
</style>
</head>
<body>
<div class="page">
  <div class="letterhead">
    <div class="lh-left">
      <img src="${window.location.origin}/simpleton-logo.jpeg" alt="Simpleton" />
      <div>
        <div class="lh-name">Simpleton&#8482;</div>
        <div class="lh-tag">Precision Pricing, Simplified.</div>
      </div>
    </div>
    <div class="lh-right">
      ${currentDate}<br/>intel@simpletonapp.com
    </div>
  </div>

  <div class="title-block">
    <h1>${title}</h1>
    ${subtitle ? `<div class="sub">${subtitle}</div>` : ''}
  </div>

  <div class="report-body">
    ${bodyContent}
  </div>

  <div class="report-footer">
    <div class="disclaimer">
      This report is generated by <span className="simpleton-brand">Simpleton</span>&#8482; and is provided for informational and educational purposes only.
      It does not constitute financial, investment, or professional advice. Market conditions change rapidly; always consult
      a qualified professional before making financial decisions. <span className="simpleton-brand">Simpleton</span>&#8482; assumes no liability for actions
      taken based on this information.
    </div>
    <div class="brand">simpletonapp.com</div>
  </div>
</div>
</body>
</html>`;
  };

  const handlePrint = () => {
    const html = buildReportHTML();
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
      }, 600);
    }
  };

  const handleSave = () => {
    const html = buildReportHTML();
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const safeName = title.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '_');
    a.download = `${safeName}_Simpleton_Vision.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="simpleton-document">
      <div className="simpleton-document-actions no-print flex items-center gap-2 mb-4">
        <button
          onClick={handlePrint}
          className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all hover:opacity-80"
          style={{ backgroundColor: 'var(--primary)', color: 'white' }}
        >
          <Printer className="w-4 h-4" />
          Print
        </button>
        <button
          onClick={handleSave}
          className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all hover:opacity-80"
          style={{ backgroundColor: 'rgba(255,255,255,0.08)', color: 'var(--foreground)', border: '1px solid rgba(255,255,255,0.12)' }}
        >
          <Download className="w-4 h-4" />
          Save as PDF
        </button>
        {onClose && (
          <button
            onClick={onClose}
            className="ml-auto flex items-center gap-1 px-3 py-2 rounded-lg text-sm transition-all hover:opacity-80"
            style={{ color: 'var(--muted-foreground)' }}
          >
            <X className="w-4 h-4" />
            Close
          </button>
        )}
      </div>

      <div className="simpleton-document-body rounded-xl overflow-hidden"
        style={{ backgroundColor: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)' }}>

        <div className="simpleton-letterhead px-8 pt-8 pb-6" style={{ borderBottom: '2px solid rgba(201,169,110,0.3)' }}>
          <div className="flex items-start justify-between">
            <div className="flex items-center gap-4">
              <img
                src="/simpleton-logo.jpeg"
                alt="Simpleton"
                className="w-14 h-14 rounded-lg object-contain"
              />
              <div>
                <h1 className="text-xl font-bold tracking-tight" style={{ color: 'var(--primary)' }}>
                  <span className="simpleton-brand">Simpleton</span>™
                </h1>
                <p className="text-xs tracking-wider uppercase mt-0.5" style={{ color: 'var(--muted-foreground)' }}>
                  Precision Pricing, Simplified.
                </p>
              </div>
            </div>
            <div className="text-right">
              <p className="text-xs" style={{ color: 'var(--muted-foreground)' }}>{currentDate}</p>
              <p className="text-xs mt-0.5" style={{ color: 'var(--muted-foreground)' }}>intel@simpletonapp.com</p>
            </div>
          </div>
        </div>

        <div className="px-8 pt-6 pb-2">
          <h2 className="text-lg font-bold tracking-tight" style={{ color: 'var(--foreground)' }}>
            {title}
          </h2>
          {subtitle && (
            <p className="text-sm mt-1" style={{ color: 'var(--muted-foreground)' }}>{subtitle}</p>
          )}
        </div>

        <div className="px-8 py-6" ref={contentRef}>
          {children}
        </div>

        <div className="simpleton-footer px-8 py-4" style={{ borderTop: '1px solid rgba(201,169,110,0.15)' }}>
          <div className="flex items-center justify-between">
            <p className="text-[10px]" style={{ color: 'var(--muted-foreground)' }}>
              This document is generated by <span className="simpleton-brand">Simpleton</span>™ and is intended for informational purposes only. It does not constitute financial advice.
            </p>
            <p className="text-[10px] font-medium" style={{ color: 'var(--primary)' }}>
              simpletonapp.com
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
